/*
eZmax API Definition (Full)

Testing ObjectEzsignsignergroupAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package eZmaxApi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/ezmaxinc/ezmax-sdk-go"
)

func Test_eZmaxApi_ObjectEzsignsignergroupAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ObjectEzsignsignergroupAPIService EzsignsignergroupCreateObjectV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ObjectEzsignsignergroupAPI.EzsignsignergroupCreateObjectV1(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ObjectEzsignsignergroupAPIService EzsignsignergroupDeleteObjectV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pkiEzsignsignergroupID int32

		resp, httpRes, err := apiClient.ObjectEzsignsignergroupAPI.EzsignsignergroupDeleteObjectV1(context.Background(), pkiEzsignsignergroupID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ObjectEzsignsignergroupAPIService EzsignsignergroupEditEzsignsignergroupmembershipsV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pkiEzsignsignergroupID int32

		resp, httpRes, err := apiClient.ObjectEzsignsignergroupAPI.EzsignsignergroupEditEzsignsignergroupmembershipsV1(context.Background(), pkiEzsignsignergroupID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ObjectEzsignsignergroupAPIService EzsignsignergroupEditObjectV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pkiEzsignsignergroupID int32

		resp, httpRes, err := apiClient.ObjectEzsignsignergroupAPI.EzsignsignergroupEditObjectV1(context.Background(), pkiEzsignsignergroupID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ObjectEzsignsignergroupAPIService EzsignsignergroupGetEzsignsignergroupmembershipsV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pkiEzsignsignergroupID int32

		resp, httpRes, err := apiClient.ObjectEzsignsignergroupAPI.EzsignsignergroupGetEzsignsignergroupmembershipsV1(context.Background(), pkiEzsignsignergroupID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ObjectEzsignsignergroupAPIService EzsignsignergroupGetObjectV2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pkiEzsignsignergroupID int32

		resp, httpRes, err := apiClient.ObjectEzsignsignergroupAPI.EzsignsignergroupGetObjectV2(context.Background(), pkiEzsignsignergroupID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
