/*
eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

API version: 1.2.1
Contact: support-api@ezmax.ca
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eZmaxApi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// ObjectEzsignbulksendsignermappingAPIService ObjectEzsignbulksendsignermappingAPI service
type ObjectEzsignbulksendsignermappingAPIService service

type ApiEzsignbulksendsignermappingCreateObjectV1Request struct {
	ctx context.Context
	ApiService *ObjectEzsignbulksendsignermappingAPIService
	ezsignbulksendsignermappingCreateObjectV1Request *EzsignbulksendsignermappingCreateObjectV1Request
}

func (r ApiEzsignbulksendsignermappingCreateObjectV1Request) EzsignbulksendsignermappingCreateObjectV1Request(ezsignbulksendsignermappingCreateObjectV1Request EzsignbulksendsignermappingCreateObjectV1Request) ApiEzsignbulksendsignermappingCreateObjectV1Request {
	r.ezsignbulksendsignermappingCreateObjectV1Request = &ezsignbulksendsignermappingCreateObjectV1Request
	return r
}

func (r ApiEzsignbulksendsignermappingCreateObjectV1Request) Execute() (*EzsignbulksendsignermappingCreateObjectV1Response, *http.Response, error) {
	return r.ApiService.EzsignbulksendsignermappingCreateObjectV1Execute(r)
}

/*
EzsignbulksendsignermappingCreateObjectV1 Create a new Ezsignbulksendsignermapping

The endpoint allows to create one or many elements at once.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiEzsignbulksendsignermappingCreateObjectV1Request
*/
func (a *ObjectEzsignbulksendsignermappingAPIService) EzsignbulksendsignermappingCreateObjectV1(ctx context.Context) ApiEzsignbulksendsignermappingCreateObjectV1Request {
	return ApiEzsignbulksendsignermappingCreateObjectV1Request{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return EzsignbulksendsignermappingCreateObjectV1Response
func (a *ObjectEzsignbulksendsignermappingAPIService) EzsignbulksendsignermappingCreateObjectV1Execute(r ApiEzsignbulksendsignermappingCreateObjectV1Request) (*EzsignbulksendsignermappingCreateObjectV1Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *EzsignbulksendsignermappingCreateObjectV1Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ObjectEzsignbulksendsignermappingAPIService.EzsignbulksendsignermappingCreateObjectV1")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/1/object/ezsignbulksendsignermapping"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.ezsignbulksendsignermappingCreateObjectV1Request == nil {
		return localVarReturnValue, nil, reportError("ezsignbulksendsignermappingCreateObjectV1Request is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.ezsignbulksendsignermappingCreateObjectV1Request
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["Authorization"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiEzsignbulksendsignermappingDeleteObjectV1Request struct {
	ctx context.Context
	ApiService *ObjectEzsignbulksendsignermappingAPIService
	pkiEzsignbulksendsignermappingID int32
}

func (r ApiEzsignbulksendsignermappingDeleteObjectV1Request) Execute() (*EzsignbulksendsignermappingDeleteObjectV1Response, *http.Response, error) {
	return r.ApiService.EzsignbulksendsignermappingDeleteObjectV1Execute(r)
}

/*
EzsignbulksendsignermappingDeleteObjectV1 Delete an existing Ezsignbulksendsignermapping



 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param pkiEzsignbulksendsignermappingID
 @return ApiEzsignbulksendsignermappingDeleteObjectV1Request
*/
func (a *ObjectEzsignbulksendsignermappingAPIService) EzsignbulksendsignermappingDeleteObjectV1(ctx context.Context, pkiEzsignbulksendsignermappingID int32) ApiEzsignbulksendsignermappingDeleteObjectV1Request {
	return ApiEzsignbulksendsignermappingDeleteObjectV1Request{
		ApiService: a,
		ctx: ctx,
		pkiEzsignbulksendsignermappingID: pkiEzsignbulksendsignermappingID,
	}
}

// Execute executes the request
//  @return EzsignbulksendsignermappingDeleteObjectV1Response
func (a *ObjectEzsignbulksendsignermappingAPIService) EzsignbulksendsignermappingDeleteObjectV1Execute(r ApiEzsignbulksendsignermappingDeleteObjectV1Request) (*EzsignbulksendsignermappingDeleteObjectV1Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *EzsignbulksendsignermappingDeleteObjectV1Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ObjectEzsignbulksendsignermappingAPIService.EzsignbulksendsignermappingDeleteObjectV1")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/1/object/ezsignbulksendsignermapping/{pkiEzsignbulksendsignermappingID}"
	localVarPath = strings.Replace(localVarPath, "{"+"pkiEzsignbulksendsignermappingID"+"}", url.PathEscape(parameterValueToString(r.pkiEzsignbulksendsignermappingID, "pkiEzsignbulksendsignermappingID")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.pkiEzsignbulksendsignermappingID < 0 {
		return localVarReturnValue, nil, reportError("pkiEzsignbulksendsignermappingID must be greater than 0")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["Authorization"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v CommonResponseError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiEzsignbulksendsignermappingGetObjectV2Request struct {
	ctx context.Context
	ApiService *ObjectEzsignbulksendsignermappingAPIService
	pkiEzsignbulksendsignermappingID int32
}

func (r ApiEzsignbulksendsignermappingGetObjectV2Request) Execute() (*EzsignbulksendsignermappingGetObjectV2Response, *http.Response, error) {
	return r.ApiService.EzsignbulksendsignermappingGetObjectV2Execute(r)
}

/*
EzsignbulksendsignermappingGetObjectV2 Retrieve an existing Ezsignbulksendsignermapping



 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param pkiEzsignbulksendsignermappingID
 @return ApiEzsignbulksendsignermappingGetObjectV2Request
*/
func (a *ObjectEzsignbulksendsignermappingAPIService) EzsignbulksendsignermappingGetObjectV2(ctx context.Context, pkiEzsignbulksendsignermappingID int32) ApiEzsignbulksendsignermappingGetObjectV2Request {
	return ApiEzsignbulksendsignermappingGetObjectV2Request{
		ApiService: a,
		ctx: ctx,
		pkiEzsignbulksendsignermappingID: pkiEzsignbulksendsignermappingID,
	}
}

// Execute executes the request
//  @return EzsignbulksendsignermappingGetObjectV2Response
func (a *ObjectEzsignbulksendsignermappingAPIService) EzsignbulksendsignermappingGetObjectV2Execute(r ApiEzsignbulksendsignermappingGetObjectV2Request) (*EzsignbulksendsignermappingGetObjectV2Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *EzsignbulksendsignermappingGetObjectV2Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ObjectEzsignbulksendsignermappingAPIService.EzsignbulksendsignermappingGetObjectV2")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/2/object/ezsignbulksendsignermapping/{pkiEzsignbulksendsignermappingID}"
	localVarPath = strings.Replace(localVarPath, "{"+"pkiEzsignbulksendsignermappingID"+"}", url.PathEscape(parameterValueToString(r.pkiEzsignbulksendsignermappingID, "pkiEzsignbulksendsignermappingID")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.pkiEzsignbulksendsignermappingID < 0 {
		return localVarReturnValue, nil, reportError("pkiEzsignbulksendsignermappingID must be greater than 0")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["Authorization"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v CommonResponseError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
