/*
eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

API version: 1.2.0
Contact: support-api@ezmax.ca
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eZmaxApi

import (
	"encoding/json"
)

// checks if the EzsignsignergroupmembershipCreateObjectV1Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EzsignsignergroupmembershipCreateObjectV1Response{}

// EzsignsignergroupmembershipCreateObjectV1Response Response for POST /1/object/ezsignsignergroupmembership
type EzsignsignergroupmembershipCreateObjectV1Response struct {
	ObjDebugPayload CommonResponseObjDebugPayload `json:"objDebugPayload"`
	ObjDebug *CommonResponseObjDebug `json:"objDebug,omitempty"`
	MPayload EzsignsignergroupmembershipCreateObjectV1ResponseMPayload `json:"mPayload"`
}

// NewEzsignsignergroupmembershipCreateObjectV1Response instantiates a new EzsignsignergroupmembershipCreateObjectV1Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEzsignsignergroupmembershipCreateObjectV1Response(objDebugPayload CommonResponseObjDebugPayload, mPayload EzsignsignergroupmembershipCreateObjectV1ResponseMPayload) *EzsignsignergroupmembershipCreateObjectV1Response {
	this := EzsignsignergroupmembershipCreateObjectV1Response{}
	this.ObjDebugPayload = objDebugPayload
	this.MPayload = mPayload
	return &this
}

// NewEzsignsignergroupmembershipCreateObjectV1ResponseWithDefaults instantiates a new EzsignsignergroupmembershipCreateObjectV1Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEzsignsignergroupmembershipCreateObjectV1ResponseWithDefaults() *EzsignsignergroupmembershipCreateObjectV1Response {
	this := EzsignsignergroupmembershipCreateObjectV1Response{}
	return &this
}

// GetObjDebugPayload returns the ObjDebugPayload field value
func (o *EzsignsignergroupmembershipCreateObjectV1Response) GetObjDebugPayload() CommonResponseObjDebugPayload {
	if o == nil {
		var ret CommonResponseObjDebugPayload
		return ret
	}

	return o.ObjDebugPayload
}

// GetObjDebugPayloadOk returns a tuple with the ObjDebugPayload field value
// and a boolean to check if the value has been set.
func (o *EzsignsignergroupmembershipCreateObjectV1Response) GetObjDebugPayloadOk() (*CommonResponseObjDebugPayload, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjDebugPayload, true
}

// SetObjDebugPayload sets field value
func (o *EzsignsignergroupmembershipCreateObjectV1Response) SetObjDebugPayload(v CommonResponseObjDebugPayload) {
	o.ObjDebugPayload = v
}

// GetObjDebug returns the ObjDebug field value if set, zero value otherwise.
func (o *EzsignsignergroupmembershipCreateObjectV1Response) GetObjDebug() CommonResponseObjDebug {
	if o == nil || IsNil(o.ObjDebug) {
		var ret CommonResponseObjDebug
		return ret
	}
	return *o.ObjDebug
}

// GetObjDebugOk returns a tuple with the ObjDebug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EzsignsignergroupmembershipCreateObjectV1Response) GetObjDebugOk() (*CommonResponseObjDebug, bool) {
	if o == nil || IsNil(o.ObjDebug) {
		return nil, false
	}
	return o.ObjDebug, true
}

// HasObjDebug returns a boolean if a field has been set.
func (o *EzsignsignergroupmembershipCreateObjectV1Response) HasObjDebug() bool {
	if o != nil && !IsNil(o.ObjDebug) {
		return true
	}

	return false
}

// SetObjDebug gets a reference to the given CommonResponseObjDebug and assigns it to the ObjDebug field.
func (o *EzsignsignergroupmembershipCreateObjectV1Response) SetObjDebug(v CommonResponseObjDebug) {
	o.ObjDebug = &v
}

// GetMPayload returns the MPayload field value
func (o *EzsignsignergroupmembershipCreateObjectV1Response) GetMPayload() EzsignsignergroupmembershipCreateObjectV1ResponseMPayload {
	if o == nil {
		var ret EzsignsignergroupmembershipCreateObjectV1ResponseMPayload
		return ret
	}

	return o.MPayload
}

// GetMPayloadOk returns a tuple with the MPayload field value
// and a boolean to check if the value has been set.
func (o *EzsignsignergroupmembershipCreateObjectV1Response) GetMPayloadOk() (*EzsignsignergroupmembershipCreateObjectV1ResponseMPayload, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MPayload, true
}

// SetMPayload sets field value
func (o *EzsignsignergroupmembershipCreateObjectV1Response) SetMPayload(v EzsignsignergroupmembershipCreateObjectV1ResponseMPayload) {
	o.MPayload = v
}

func (o EzsignsignergroupmembershipCreateObjectV1Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EzsignsignergroupmembershipCreateObjectV1Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["objDebugPayload"] = o.ObjDebugPayload
	if !IsNil(o.ObjDebug) {
		toSerialize["objDebug"] = o.ObjDebug
	}
	toSerialize["mPayload"] = o.MPayload
	return toSerialize, nil
}

type NullableEzsignsignergroupmembershipCreateObjectV1Response struct {
	value *EzsignsignergroupmembershipCreateObjectV1Response
	isSet bool
}

func (v NullableEzsignsignergroupmembershipCreateObjectV1Response) Get() *EzsignsignergroupmembershipCreateObjectV1Response {
	return v.value
}

func (v *NullableEzsignsignergroupmembershipCreateObjectV1Response) Set(val *EzsignsignergroupmembershipCreateObjectV1Response) {
	v.value = val
	v.isSet = true
}

func (v NullableEzsignsignergroupmembershipCreateObjectV1Response) IsSet() bool {
	return v.isSet
}

func (v *NullableEzsignsignergroupmembershipCreateObjectV1Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEzsignsignergroupmembershipCreateObjectV1Response(val *EzsignsignergroupmembershipCreateObjectV1Response) *NullableEzsignsignergroupmembershipCreateObjectV1Response {
	return &NullableEzsignsignergroupmembershipCreateObjectV1Response{value: val, isSet: true}
}

func (v NullableEzsignsignergroupmembershipCreateObjectV1Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEzsignsignergroupmembershipCreateObjectV1Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


