/*
eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

API version: 1.3.4
Contact: support-api@ezmax.ca
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eZmaxApi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EzsignbulksendGetObjectV4Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EzsignbulksendGetObjectV4Response{}

// EzsignbulksendGetObjectV4Response Response for GET /4/object/ezsignbulksend/{pkiEzsignbulksendID}
type EzsignbulksendGetObjectV4Response struct {
	ObjDebugPayload CommonResponseObjDebugPayload `json:"objDebugPayload"`
	ObjDebug *CommonResponseObjDebug `json:"objDebug,omitempty"`
	MPayload EzsignbulksendGetObjectV4ResponseMPayload `json:"mPayload"`
}

type _EzsignbulksendGetObjectV4Response EzsignbulksendGetObjectV4Response

// NewEzsignbulksendGetObjectV4Response instantiates a new EzsignbulksendGetObjectV4Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEzsignbulksendGetObjectV4Response(objDebugPayload CommonResponseObjDebugPayload, mPayload EzsignbulksendGetObjectV4ResponseMPayload) *EzsignbulksendGetObjectV4Response {
	this := EzsignbulksendGetObjectV4Response{}
	this.ObjDebugPayload = objDebugPayload
	this.MPayload = mPayload
	return &this
}

// NewEzsignbulksendGetObjectV4ResponseWithDefaults instantiates a new EzsignbulksendGetObjectV4Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEzsignbulksendGetObjectV4ResponseWithDefaults() *EzsignbulksendGetObjectV4Response {
	this := EzsignbulksendGetObjectV4Response{}
	return &this
}

// GetObjDebugPayload returns the ObjDebugPayload field value
func (o *EzsignbulksendGetObjectV4Response) GetObjDebugPayload() CommonResponseObjDebugPayload {
	if o == nil {
		var ret CommonResponseObjDebugPayload
		return ret
	}

	return o.ObjDebugPayload
}

// GetObjDebugPayloadOk returns a tuple with the ObjDebugPayload field value
// and a boolean to check if the value has been set.
func (o *EzsignbulksendGetObjectV4Response) GetObjDebugPayloadOk() (*CommonResponseObjDebugPayload, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjDebugPayload, true
}

// SetObjDebugPayload sets field value
func (o *EzsignbulksendGetObjectV4Response) SetObjDebugPayload(v CommonResponseObjDebugPayload) {
	o.ObjDebugPayload = v
}

// GetObjDebug returns the ObjDebug field value if set, zero value otherwise.
func (o *EzsignbulksendGetObjectV4Response) GetObjDebug() CommonResponseObjDebug {
	if o == nil || IsNil(o.ObjDebug) {
		var ret CommonResponseObjDebug
		return ret
	}
	return *o.ObjDebug
}

// GetObjDebugOk returns a tuple with the ObjDebug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EzsignbulksendGetObjectV4Response) GetObjDebugOk() (*CommonResponseObjDebug, bool) {
	if o == nil || IsNil(o.ObjDebug) {
		return nil, false
	}
	return o.ObjDebug, true
}

// HasObjDebug returns a boolean if a field has been set.
func (o *EzsignbulksendGetObjectV4Response) HasObjDebug() bool {
	if o != nil && !IsNil(o.ObjDebug) {
		return true
	}

	return false
}

// SetObjDebug gets a reference to the given CommonResponseObjDebug and assigns it to the ObjDebug field.
func (o *EzsignbulksendGetObjectV4Response) SetObjDebug(v CommonResponseObjDebug) {
	o.ObjDebug = &v
}

// GetMPayload returns the MPayload field value
func (o *EzsignbulksendGetObjectV4Response) GetMPayload() EzsignbulksendGetObjectV4ResponseMPayload {
	if o == nil {
		var ret EzsignbulksendGetObjectV4ResponseMPayload
		return ret
	}

	return o.MPayload
}

// GetMPayloadOk returns a tuple with the MPayload field value
// and a boolean to check if the value has been set.
func (o *EzsignbulksendGetObjectV4Response) GetMPayloadOk() (*EzsignbulksendGetObjectV4ResponseMPayload, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MPayload, true
}

// SetMPayload sets field value
func (o *EzsignbulksendGetObjectV4Response) SetMPayload(v EzsignbulksendGetObjectV4ResponseMPayload) {
	o.MPayload = v
}

func (o EzsignbulksendGetObjectV4Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EzsignbulksendGetObjectV4Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["objDebugPayload"] = o.ObjDebugPayload
	if !IsNil(o.ObjDebug) {
		toSerialize["objDebug"] = o.ObjDebug
	}
	toSerialize["mPayload"] = o.MPayload
	return toSerialize, nil
}

func (o *EzsignbulksendGetObjectV4Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"objDebugPayload",
		"mPayload",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEzsignbulksendGetObjectV4Response := _EzsignbulksendGetObjectV4Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEzsignbulksendGetObjectV4Response)

	if err != nil {
		return err
	}

	*o = EzsignbulksendGetObjectV4Response(varEzsignbulksendGetObjectV4Response)

	return err
}

type NullableEzsignbulksendGetObjectV4Response struct {
	value *EzsignbulksendGetObjectV4Response
	isSet bool
}

func (v NullableEzsignbulksendGetObjectV4Response) Get() *EzsignbulksendGetObjectV4Response {
	return v.value
}

func (v *NullableEzsignbulksendGetObjectV4Response) Set(val *EzsignbulksendGetObjectV4Response) {
	v.value = val
	v.isSet = true
}

func (v NullableEzsignbulksendGetObjectV4Response) IsSet() bool {
	return v.isSet
}

func (v *NullableEzsignbulksendGetObjectV4Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEzsignbulksendGetObjectV4Response(val *EzsignbulksendGetObjectV4Response) *NullableEzsignbulksendGetObjectV4Response {
	return &NullableEzsignbulksendGetObjectV4Response{value: val, isSet: true}
}

func (v NullableEzsignbulksendGetObjectV4Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEzsignbulksendGetObjectV4Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


