/*
eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

API version: 1.2.2
Contact: support-api@ezmax.ca
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eZmaxApi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuthenticationexternalGetObjectV2ResponseMPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthenticationexternalGetObjectV2ResponseMPayload{}

// AuthenticationexternalGetObjectV2ResponseMPayload Payload for GET /2/object/authenticationexternal/{pkiAuthenticationexternalID}
type AuthenticationexternalGetObjectV2ResponseMPayload struct {
	ObjAuthenticationexternal AuthenticationexternalResponseCompound `json:"objAuthenticationexternal"`
}

type _AuthenticationexternalGetObjectV2ResponseMPayload AuthenticationexternalGetObjectV2ResponseMPayload

// NewAuthenticationexternalGetObjectV2ResponseMPayload instantiates a new AuthenticationexternalGetObjectV2ResponseMPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthenticationexternalGetObjectV2ResponseMPayload(objAuthenticationexternal AuthenticationexternalResponseCompound) *AuthenticationexternalGetObjectV2ResponseMPayload {
	this := AuthenticationexternalGetObjectV2ResponseMPayload{}
	this.ObjAuthenticationexternal = objAuthenticationexternal
	return &this
}

// NewAuthenticationexternalGetObjectV2ResponseMPayloadWithDefaults instantiates a new AuthenticationexternalGetObjectV2ResponseMPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthenticationexternalGetObjectV2ResponseMPayloadWithDefaults() *AuthenticationexternalGetObjectV2ResponseMPayload {
	this := AuthenticationexternalGetObjectV2ResponseMPayload{}
	return &this
}

// GetObjAuthenticationexternal returns the ObjAuthenticationexternal field value
func (o *AuthenticationexternalGetObjectV2ResponseMPayload) GetObjAuthenticationexternal() AuthenticationexternalResponseCompound {
	if o == nil {
		var ret AuthenticationexternalResponseCompound
		return ret
	}

	return o.ObjAuthenticationexternal
}

// GetObjAuthenticationexternalOk returns a tuple with the ObjAuthenticationexternal field value
// and a boolean to check if the value has been set.
func (o *AuthenticationexternalGetObjectV2ResponseMPayload) GetObjAuthenticationexternalOk() (*AuthenticationexternalResponseCompound, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjAuthenticationexternal, true
}

// SetObjAuthenticationexternal sets field value
func (o *AuthenticationexternalGetObjectV2ResponseMPayload) SetObjAuthenticationexternal(v AuthenticationexternalResponseCompound) {
	o.ObjAuthenticationexternal = v
}

func (o AuthenticationexternalGetObjectV2ResponseMPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthenticationexternalGetObjectV2ResponseMPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["objAuthenticationexternal"] = o.ObjAuthenticationexternal
	return toSerialize, nil
}

func (o *AuthenticationexternalGetObjectV2ResponseMPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"objAuthenticationexternal",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthenticationexternalGetObjectV2ResponseMPayload := _AuthenticationexternalGetObjectV2ResponseMPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthenticationexternalGetObjectV2ResponseMPayload)

	if err != nil {
		return err
	}

	*o = AuthenticationexternalGetObjectV2ResponseMPayload(varAuthenticationexternalGetObjectV2ResponseMPayload)

	return err
}

type NullableAuthenticationexternalGetObjectV2ResponseMPayload struct {
	value *AuthenticationexternalGetObjectV2ResponseMPayload
	isSet bool
}

func (v NullableAuthenticationexternalGetObjectV2ResponseMPayload) Get() *AuthenticationexternalGetObjectV2ResponseMPayload {
	return v.value
}

func (v *NullableAuthenticationexternalGetObjectV2ResponseMPayload) Set(val *AuthenticationexternalGetObjectV2ResponseMPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthenticationexternalGetObjectV2ResponseMPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthenticationexternalGetObjectV2ResponseMPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthenticationexternalGetObjectV2ResponseMPayload(val *AuthenticationexternalGetObjectV2ResponseMPayload) *NullableAuthenticationexternalGetObjectV2ResponseMPayload {
	return &NullableAuthenticationexternalGetObjectV2ResponseMPayload{value: val, isSet: true}
}

func (v NullableAuthenticationexternalGetObjectV2ResponseMPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthenticationexternalGetObjectV2ResponseMPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


