/*
eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

API version: 1.3.2
Contact: support-api@ezmax.ca
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eZmaxApi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request{}

// InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request Request for POST /1/object/inscriptionnotauthenticated/{pkiInscriptionnotauthenticatedID}/fillInscriptionnotauthenticatedcondition
type InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request struct {
	AObjInscriptionnotauthenticatedcondition []CustomInscriptionnotauthenticatedconditionRequest `json:"a_objInscriptionnotauthenticatedcondition"`
	// The transactiondatereal of the Inscriptionnotauthenticated
	DtInscriptionnotauthenticatedTransactiondateReal *string `json:"dtInscriptionnotauthenticatedTransactiondateReal,omitempty" validate:"regexp=^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$"`
}

type _InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request

// NewInscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request instantiates a new InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request(aObjInscriptionnotauthenticatedcondition []CustomInscriptionnotauthenticatedconditionRequest) *InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request {
	this := InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request{}
	this.AObjInscriptionnotauthenticatedcondition = aObjInscriptionnotauthenticatedcondition
	return &this
}

// NewInscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1RequestWithDefaults instantiates a new InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1RequestWithDefaults() *InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request {
	this := InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request{}
	return &this
}

// GetAObjInscriptionnotauthenticatedcondition returns the AObjInscriptionnotauthenticatedcondition field value
func (o *InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request) GetAObjInscriptionnotauthenticatedcondition() []CustomInscriptionnotauthenticatedconditionRequest {
	if o == nil {
		var ret []CustomInscriptionnotauthenticatedconditionRequest
		return ret
	}

	return o.AObjInscriptionnotauthenticatedcondition
}

// GetAObjInscriptionnotauthenticatedconditionOk returns a tuple with the AObjInscriptionnotauthenticatedcondition field value
// and a boolean to check if the value has been set.
func (o *InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request) GetAObjInscriptionnotauthenticatedconditionOk() ([]CustomInscriptionnotauthenticatedconditionRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.AObjInscriptionnotauthenticatedcondition, true
}

// SetAObjInscriptionnotauthenticatedcondition sets field value
func (o *InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request) SetAObjInscriptionnotauthenticatedcondition(v []CustomInscriptionnotauthenticatedconditionRequest) {
	o.AObjInscriptionnotauthenticatedcondition = v
}

// GetDtInscriptionnotauthenticatedTransactiondateReal returns the DtInscriptionnotauthenticatedTransactiondateReal field value if set, zero value otherwise.
func (o *InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request) GetDtInscriptionnotauthenticatedTransactiondateReal() string {
	if o == nil || IsNil(o.DtInscriptionnotauthenticatedTransactiondateReal) {
		var ret string
		return ret
	}
	return *o.DtInscriptionnotauthenticatedTransactiondateReal
}

// GetDtInscriptionnotauthenticatedTransactiondateRealOk returns a tuple with the DtInscriptionnotauthenticatedTransactiondateReal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request) GetDtInscriptionnotauthenticatedTransactiondateRealOk() (*string, bool) {
	if o == nil || IsNil(o.DtInscriptionnotauthenticatedTransactiondateReal) {
		return nil, false
	}
	return o.DtInscriptionnotauthenticatedTransactiondateReal, true
}

// HasDtInscriptionnotauthenticatedTransactiondateReal returns a boolean if a field has been set.
func (o *InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request) HasDtInscriptionnotauthenticatedTransactiondateReal() bool {
	if o != nil && !IsNil(o.DtInscriptionnotauthenticatedTransactiondateReal) {
		return true
	}

	return false
}

// SetDtInscriptionnotauthenticatedTransactiondateReal gets a reference to the given string and assigns it to the DtInscriptionnotauthenticatedTransactiondateReal field.
func (o *InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request) SetDtInscriptionnotauthenticatedTransactiondateReal(v string) {
	o.DtInscriptionnotauthenticatedTransactiondateReal = &v
}

func (o InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["a_objInscriptionnotauthenticatedcondition"] = o.AObjInscriptionnotauthenticatedcondition
	if !IsNil(o.DtInscriptionnotauthenticatedTransactiondateReal) {
		toSerialize["dtInscriptionnotauthenticatedTransactiondateReal"] = o.DtInscriptionnotauthenticatedTransactiondateReal
	}
	return toSerialize, nil
}

func (o *InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"a_objInscriptionnotauthenticatedcondition",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request := _InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request)

	if err != nil {
		return err
	}

	*o = InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request(varInscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request)

	return err
}

type NullableInscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request struct {
	value *InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request
	isSet bool
}

func (v NullableInscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request) Get() *InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request {
	return v.value
}

func (v *NullableInscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request) Set(val *InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request) {
	v.value = val
	v.isSet = true
}

func (v NullableInscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request) IsSet() bool {
	return v.isSet
}

func (v *NullableInscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request(val *InscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request) *NullableInscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request {
	return &NullableInscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request{value: val, isSet: true}
}

func (v NullableInscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1Request) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


