/*
eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

API version: 1.3.3
Contact: support-api@ezmax.ca
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eZmaxApi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CustomEzmaxcustomeruserResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomEzmaxcustomeruserResponse{}

// CustomEzmaxcustomeruserResponse A Ezmaxcustomeruser Object
type CustomEzmaxcustomeruserResponse struct {
	ObjEzmaxcustomer CustomEzmaxcustomerResponse `json:"objEzmaxcustomer"`
	// The unique ID of the Contacttitle.  Valid values:  |Value|Description| |-|-| |1|Ms.| |2|Mr.| |4|(Blank)| |5|Me (For Notaries)|
	FkiContacttitleID int32 `json:"fkiContacttitleID"`
	// The unique ID of the Language.  Valid values:  |Value|Description| |-|-| |1|French| |2|English|
	FkiLanguageID int32 `json:"fkiLanguageID"`
	ObjEmail *EmailResponseCompound `json:"objEmail,omitempty"`
	ObjPhone *PhoneResponseCompound `json:"objPhone,omitempty"`
	// The First name of the Ezmaxcustomeruser
	SEzmaxcustomeruserFirstname string `json:"sEzmaxcustomeruserFirstname" validate:"regexp=^.{1\\,20}$"`
	// The First name of the Ezmaxcustomeruser
	SEzmaxcustomeruserLastname string `json:"sEzmaxcustomeruserLastname" validate:"regexp=^.{1\\,20}$"`
}

type _CustomEzmaxcustomeruserResponse CustomEzmaxcustomeruserResponse

// NewCustomEzmaxcustomeruserResponse instantiates a new CustomEzmaxcustomeruserResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomEzmaxcustomeruserResponse(objEzmaxcustomer CustomEzmaxcustomerResponse, fkiContacttitleID int32, fkiLanguageID int32, sEzmaxcustomeruserFirstname string, sEzmaxcustomeruserLastname string) *CustomEzmaxcustomeruserResponse {
	this := CustomEzmaxcustomeruserResponse{}
	this.ObjEzmaxcustomer = objEzmaxcustomer
	this.FkiContacttitleID = fkiContacttitleID
	this.FkiLanguageID = fkiLanguageID
	this.SEzmaxcustomeruserFirstname = sEzmaxcustomeruserFirstname
	this.SEzmaxcustomeruserLastname = sEzmaxcustomeruserLastname
	return &this
}

// NewCustomEzmaxcustomeruserResponseWithDefaults instantiates a new CustomEzmaxcustomeruserResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomEzmaxcustomeruserResponseWithDefaults() *CustomEzmaxcustomeruserResponse {
	this := CustomEzmaxcustomeruserResponse{}
	return &this
}

// GetObjEzmaxcustomer returns the ObjEzmaxcustomer field value
func (o *CustomEzmaxcustomeruserResponse) GetObjEzmaxcustomer() CustomEzmaxcustomerResponse {
	if o == nil {
		var ret CustomEzmaxcustomerResponse
		return ret
	}

	return o.ObjEzmaxcustomer
}

// GetObjEzmaxcustomerOk returns a tuple with the ObjEzmaxcustomer field value
// and a boolean to check if the value has been set.
func (o *CustomEzmaxcustomeruserResponse) GetObjEzmaxcustomerOk() (*CustomEzmaxcustomerResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjEzmaxcustomer, true
}

// SetObjEzmaxcustomer sets field value
func (o *CustomEzmaxcustomeruserResponse) SetObjEzmaxcustomer(v CustomEzmaxcustomerResponse) {
	o.ObjEzmaxcustomer = v
}

// GetFkiContacttitleID returns the FkiContacttitleID field value
func (o *CustomEzmaxcustomeruserResponse) GetFkiContacttitleID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FkiContacttitleID
}

// GetFkiContacttitleIDOk returns a tuple with the FkiContacttitleID field value
// and a boolean to check if the value has been set.
func (o *CustomEzmaxcustomeruserResponse) GetFkiContacttitleIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FkiContacttitleID, true
}

// SetFkiContacttitleID sets field value
func (o *CustomEzmaxcustomeruserResponse) SetFkiContacttitleID(v int32) {
	o.FkiContacttitleID = v
}

// GetFkiLanguageID returns the FkiLanguageID field value
func (o *CustomEzmaxcustomeruserResponse) GetFkiLanguageID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FkiLanguageID
}

// GetFkiLanguageIDOk returns a tuple with the FkiLanguageID field value
// and a boolean to check if the value has been set.
func (o *CustomEzmaxcustomeruserResponse) GetFkiLanguageIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FkiLanguageID, true
}

// SetFkiLanguageID sets field value
func (o *CustomEzmaxcustomeruserResponse) SetFkiLanguageID(v int32) {
	o.FkiLanguageID = v
}

// GetObjEmail returns the ObjEmail field value if set, zero value otherwise.
func (o *CustomEzmaxcustomeruserResponse) GetObjEmail() EmailResponseCompound {
	if o == nil || IsNil(o.ObjEmail) {
		var ret EmailResponseCompound
		return ret
	}
	return *o.ObjEmail
}

// GetObjEmailOk returns a tuple with the ObjEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomEzmaxcustomeruserResponse) GetObjEmailOk() (*EmailResponseCompound, bool) {
	if o == nil || IsNil(o.ObjEmail) {
		return nil, false
	}
	return o.ObjEmail, true
}

// HasObjEmail returns a boolean if a field has been set.
func (o *CustomEzmaxcustomeruserResponse) HasObjEmail() bool {
	if o != nil && !IsNil(o.ObjEmail) {
		return true
	}

	return false
}

// SetObjEmail gets a reference to the given EmailResponseCompound and assigns it to the ObjEmail field.
func (o *CustomEzmaxcustomeruserResponse) SetObjEmail(v EmailResponseCompound) {
	o.ObjEmail = &v
}

// GetObjPhone returns the ObjPhone field value if set, zero value otherwise.
func (o *CustomEzmaxcustomeruserResponse) GetObjPhone() PhoneResponseCompound {
	if o == nil || IsNil(o.ObjPhone) {
		var ret PhoneResponseCompound
		return ret
	}
	return *o.ObjPhone
}

// GetObjPhoneOk returns a tuple with the ObjPhone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomEzmaxcustomeruserResponse) GetObjPhoneOk() (*PhoneResponseCompound, bool) {
	if o == nil || IsNil(o.ObjPhone) {
		return nil, false
	}
	return o.ObjPhone, true
}

// HasObjPhone returns a boolean if a field has been set.
func (o *CustomEzmaxcustomeruserResponse) HasObjPhone() bool {
	if o != nil && !IsNil(o.ObjPhone) {
		return true
	}

	return false
}

// SetObjPhone gets a reference to the given PhoneResponseCompound and assigns it to the ObjPhone field.
func (o *CustomEzmaxcustomeruserResponse) SetObjPhone(v PhoneResponseCompound) {
	o.ObjPhone = &v
}

// GetSEzmaxcustomeruserFirstname returns the SEzmaxcustomeruserFirstname field value
func (o *CustomEzmaxcustomeruserResponse) GetSEzmaxcustomeruserFirstname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SEzmaxcustomeruserFirstname
}

// GetSEzmaxcustomeruserFirstnameOk returns a tuple with the SEzmaxcustomeruserFirstname field value
// and a boolean to check if the value has been set.
func (o *CustomEzmaxcustomeruserResponse) GetSEzmaxcustomeruserFirstnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SEzmaxcustomeruserFirstname, true
}

// SetSEzmaxcustomeruserFirstname sets field value
func (o *CustomEzmaxcustomeruserResponse) SetSEzmaxcustomeruserFirstname(v string) {
	o.SEzmaxcustomeruserFirstname = v
}

// GetSEzmaxcustomeruserLastname returns the SEzmaxcustomeruserLastname field value
func (o *CustomEzmaxcustomeruserResponse) GetSEzmaxcustomeruserLastname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SEzmaxcustomeruserLastname
}

// GetSEzmaxcustomeruserLastnameOk returns a tuple with the SEzmaxcustomeruserLastname field value
// and a boolean to check if the value has been set.
func (o *CustomEzmaxcustomeruserResponse) GetSEzmaxcustomeruserLastnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SEzmaxcustomeruserLastname, true
}

// SetSEzmaxcustomeruserLastname sets field value
func (o *CustomEzmaxcustomeruserResponse) SetSEzmaxcustomeruserLastname(v string) {
	o.SEzmaxcustomeruserLastname = v
}

func (o CustomEzmaxcustomeruserResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomEzmaxcustomeruserResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["objEzmaxcustomer"] = o.ObjEzmaxcustomer
	toSerialize["fkiContacttitleID"] = o.FkiContacttitleID
	toSerialize["fkiLanguageID"] = o.FkiLanguageID
	if !IsNil(o.ObjEmail) {
		toSerialize["objEmail"] = o.ObjEmail
	}
	if !IsNil(o.ObjPhone) {
		toSerialize["objPhone"] = o.ObjPhone
	}
	toSerialize["sEzmaxcustomeruserFirstname"] = o.SEzmaxcustomeruserFirstname
	toSerialize["sEzmaxcustomeruserLastname"] = o.SEzmaxcustomeruserLastname
	return toSerialize, nil
}

func (o *CustomEzmaxcustomeruserResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"objEzmaxcustomer",
		"fkiContacttitleID",
		"fkiLanguageID",
		"sEzmaxcustomeruserFirstname",
		"sEzmaxcustomeruserLastname",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomEzmaxcustomeruserResponse := _CustomEzmaxcustomeruserResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCustomEzmaxcustomeruserResponse)

	if err != nil {
		return err
	}

	*o = CustomEzmaxcustomeruserResponse(varCustomEzmaxcustomeruserResponse)

	return err
}

type NullableCustomEzmaxcustomeruserResponse struct {
	value *CustomEzmaxcustomeruserResponse
	isSet bool
}

func (v NullableCustomEzmaxcustomeruserResponse) Get() *CustomEzmaxcustomeruserResponse {
	return v.value
}

func (v *NullableCustomEzmaxcustomeruserResponse) Set(val *CustomEzmaxcustomeruserResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomEzmaxcustomeruserResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomEzmaxcustomeruserResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomEzmaxcustomeruserResponse(val *CustomEzmaxcustomeruserResponse) *NullableCustomEzmaxcustomeruserResponse {
	return &NullableCustomEzmaxcustomeruserResponse{value: val, isSet: true}
}

func (v NullableCustomEzmaxcustomeruserResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomEzmaxcustomeruserResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


