/*
eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

API version: 1.2.1
Contact: support-api@ezmax.ca
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eZmaxApi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SessionhistoryGetListV1ResponseMPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionhistoryGetListV1ResponseMPayload{}

// SessionhistoryGetListV1ResponseMPayload Payload for GET /1/object/sessionhistory/getList
type SessionhistoryGetListV1ResponseMPayload struct {
	CommonGetListV1ResponseMPayload
	AObjSessionhistory []SessionhistoryListElement `json:"a_objSessionhistory"`
}

type _SessionhistoryGetListV1ResponseMPayload SessionhistoryGetListV1ResponseMPayload

// NewSessionhistoryGetListV1ResponseMPayload instantiates a new SessionhistoryGetListV1ResponseMPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionhistoryGetListV1ResponseMPayload(aObjSessionhistory []SessionhistoryListElement, iRowReturned int32, iRowFiltered int32) *SessionhistoryGetListV1ResponseMPayload {
	this := SessionhistoryGetListV1ResponseMPayload{}
	this.IRowReturned = iRowReturned
	this.IRowFiltered = iRowFiltered
	this.AObjSessionhistory = aObjSessionhistory
	return &this
}

// NewSessionhistoryGetListV1ResponseMPayloadWithDefaults instantiates a new SessionhistoryGetListV1ResponseMPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionhistoryGetListV1ResponseMPayloadWithDefaults() *SessionhistoryGetListV1ResponseMPayload {
	this := SessionhistoryGetListV1ResponseMPayload{}
	return &this
}

// GetAObjSessionhistory returns the AObjSessionhistory field value
func (o *SessionhistoryGetListV1ResponseMPayload) GetAObjSessionhistory() []SessionhistoryListElement {
	if o == nil {
		var ret []SessionhistoryListElement
		return ret
	}

	return o.AObjSessionhistory
}

// GetAObjSessionhistoryOk returns a tuple with the AObjSessionhistory field value
// and a boolean to check if the value has been set.
func (o *SessionhistoryGetListV1ResponseMPayload) GetAObjSessionhistoryOk() ([]SessionhistoryListElement, bool) {
	if o == nil {
		return nil, false
	}
	return o.AObjSessionhistory, true
}

// SetAObjSessionhistory sets field value
func (o *SessionhistoryGetListV1ResponseMPayload) SetAObjSessionhistory(v []SessionhistoryListElement) {
	o.AObjSessionhistory = v
}

func (o SessionhistoryGetListV1ResponseMPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionhistoryGetListV1ResponseMPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["a_objSessionhistory"] = o.AObjSessionhistory
	return toSerialize, nil
}

func (o *SessionhistoryGetListV1ResponseMPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"a_objSessionhistory",
		"iRowReturned",
		"iRowFiltered",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSessionhistoryGetListV1ResponseMPayload := _SessionhistoryGetListV1ResponseMPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSessionhistoryGetListV1ResponseMPayload)

	if err != nil {
		return err
	}

	*o = SessionhistoryGetListV1ResponseMPayload(varSessionhistoryGetListV1ResponseMPayload)

	return err
}

type NullableSessionhistoryGetListV1ResponseMPayload struct {
	value *SessionhistoryGetListV1ResponseMPayload
	isSet bool
}

func (v NullableSessionhistoryGetListV1ResponseMPayload) Get() *SessionhistoryGetListV1ResponseMPayload {
	return v.value
}

func (v *NullableSessionhistoryGetListV1ResponseMPayload) Set(val *SessionhistoryGetListV1ResponseMPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionhistoryGetListV1ResponseMPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionhistoryGetListV1ResponseMPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionhistoryGetListV1ResponseMPayload(val *SessionhistoryGetListV1ResponseMPayload) *NullableSessionhistoryGetListV1ResponseMPayload {
	return &NullableSessionhistoryGetListV1ResponseMPayload{value: val, isSet: true}
}

func (v NullableSessionhistoryGetListV1ResponseMPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionhistoryGetListV1ResponseMPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


