/*
eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

API version: 1.3.3
Contact: support-api@ezmax.ca
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eZmaxApi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EzsignfoldersignerassociationEditObjectV2Request type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EzsignfoldersignerassociationEditObjectV2Request{}

// EzsignfoldersignerassociationEditObjectV2Request Request for PUT /2/object/ezsignfoldersignerassociation/{pkiEzsignfoldersignerassociationID}
type EzsignfoldersignerassociationEditObjectV2Request struct {
	ObjEzsignfoldersignerassociation EzsignfoldersignerassociationRequestCompoundV2 `json:"objEzsignfoldersignerassociation"`
}

type _EzsignfoldersignerassociationEditObjectV2Request EzsignfoldersignerassociationEditObjectV2Request

// NewEzsignfoldersignerassociationEditObjectV2Request instantiates a new EzsignfoldersignerassociationEditObjectV2Request object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEzsignfoldersignerassociationEditObjectV2Request(objEzsignfoldersignerassociation EzsignfoldersignerassociationRequestCompoundV2) *EzsignfoldersignerassociationEditObjectV2Request {
	this := EzsignfoldersignerassociationEditObjectV2Request{}
	this.ObjEzsignfoldersignerassociation = objEzsignfoldersignerassociation
	return &this
}

// NewEzsignfoldersignerassociationEditObjectV2RequestWithDefaults instantiates a new EzsignfoldersignerassociationEditObjectV2Request object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEzsignfoldersignerassociationEditObjectV2RequestWithDefaults() *EzsignfoldersignerassociationEditObjectV2Request {
	this := EzsignfoldersignerassociationEditObjectV2Request{}
	return &this
}

// GetObjEzsignfoldersignerassociation returns the ObjEzsignfoldersignerassociation field value
func (o *EzsignfoldersignerassociationEditObjectV2Request) GetObjEzsignfoldersignerassociation() EzsignfoldersignerassociationRequestCompoundV2 {
	if o == nil {
		var ret EzsignfoldersignerassociationRequestCompoundV2
		return ret
	}

	return o.ObjEzsignfoldersignerassociation
}

// GetObjEzsignfoldersignerassociationOk returns a tuple with the ObjEzsignfoldersignerassociation field value
// and a boolean to check if the value has been set.
func (o *EzsignfoldersignerassociationEditObjectV2Request) GetObjEzsignfoldersignerassociationOk() (*EzsignfoldersignerassociationRequestCompoundV2, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjEzsignfoldersignerassociation, true
}

// SetObjEzsignfoldersignerassociation sets field value
func (o *EzsignfoldersignerassociationEditObjectV2Request) SetObjEzsignfoldersignerassociation(v EzsignfoldersignerassociationRequestCompoundV2) {
	o.ObjEzsignfoldersignerassociation = v
}

func (o EzsignfoldersignerassociationEditObjectV2Request) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EzsignfoldersignerassociationEditObjectV2Request) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["objEzsignfoldersignerassociation"] = o.ObjEzsignfoldersignerassociation
	return toSerialize, nil
}

func (o *EzsignfoldersignerassociationEditObjectV2Request) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"objEzsignfoldersignerassociation",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEzsignfoldersignerassociationEditObjectV2Request := _EzsignfoldersignerassociationEditObjectV2Request{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEzsignfoldersignerassociationEditObjectV2Request)

	if err != nil {
		return err
	}

	*o = EzsignfoldersignerassociationEditObjectV2Request(varEzsignfoldersignerassociationEditObjectV2Request)

	return err
}

type NullableEzsignfoldersignerassociationEditObjectV2Request struct {
	value *EzsignfoldersignerassociationEditObjectV2Request
	isSet bool
}

func (v NullableEzsignfoldersignerassociationEditObjectV2Request) Get() *EzsignfoldersignerassociationEditObjectV2Request {
	return v.value
}

func (v *NullableEzsignfoldersignerassociationEditObjectV2Request) Set(val *EzsignfoldersignerassociationEditObjectV2Request) {
	v.value = val
	v.isSet = true
}

func (v NullableEzsignfoldersignerassociationEditObjectV2Request) IsSet() bool {
	return v.isSet
}

func (v *NullableEzsignfoldersignerassociationEditObjectV2Request) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEzsignfoldersignerassociationEditObjectV2Request(val *EzsignfoldersignerassociationEditObjectV2Request) *NullableEzsignfoldersignerassociationEditObjectV2Request {
	return &NullableEzsignfoldersignerassociationEditObjectV2Request{value: val, isSet: true}
}

func (v NullableEzsignfoldersignerassociationEditObjectV2Request) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEzsignfoldersignerassociationEditObjectV2Request) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


