/*
eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

API version: 1.2.1
Contact: support-api@ezmax.ca
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eZmaxApi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SignatureDeleteObjectV1Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignatureDeleteObjectV1Response{}

// SignatureDeleteObjectV1Response Response for DELETE /1/object/signature/{pkiSignatureID}
type SignatureDeleteObjectV1Response struct {
	CommonResponse
}

type _SignatureDeleteObjectV1Response SignatureDeleteObjectV1Response

// NewSignatureDeleteObjectV1Response instantiates a new SignatureDeleteObjectV1Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignatureDeleteObjectV1Response(objDebugPayload CommonResponseObjDebugPayload) *SignatureDeleteObjectV1Response {
	this := SignatureDeleteObjectV1Response{}
	this.ObjDebugPayload = objDebugPayload
	return &this
}

// NewSignatureDeleteObjectV1ResponseWithDefaults instantiates a new SignatureDeleteObjectV1Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignatureDeleteObjectV1ResponseWithDefaults() *SignatureDeleteObjectV1Response {
	this := SignatureDeleteObjectV1Response{}
	return &this
}

func (o SignatureDeleteObjectV1Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignatureDeleteObjectV1Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

func (o *SignatureDeleteObjectV1Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"objDebugPayload",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSignatureDeleteObjectV1Response := _SignatureDeleteObjectV1Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSignatureDeleteObjectV1Response)

	if err != nil {
		return err
	}

	*o = SignatureDeleteObjectV1Response(varSignatureDeleteObjectV1Response)

	return err
}

type NullableSignatureDeleteObjectV1Response struct {
	value *SignatureDeleteObjectV1Response
	isSet bool
}

func (v NullableSignatureDeleteObjectV1Response) Get() *SignatureDeleteObjectV1Response {
	return v.value
}

func (v *NullableSignatureDeleteObjectV1Response) Set(val *SignatureDeleteObjectV1Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSignatureDeleteObjectV1Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSignatureDeleteObjectV1Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignatureDeleteObjectV1Response(val *SignatureDeleteObjectV1Response) *NullableSignatureDeleteObjectV1Response {
	return &NullableSignatureDeleteObjectV1Response{value: val, isSet: true}
}

func (v NullableSignatureDeleteObjectV1Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignatureDeleteObjectV1Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


