/*
eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

API version: 1.2.1
Contact: support-api@ezmax.ca
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eZmaxApi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EzsignfoldersignerassociationEditObjectV1Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EzsignfoldersignerassociationEditObjectV1Response{}

// EzsignfoldersignerassociationEditObjectV1Response Response for PUT /1/object/ezsignfoldersignerassociation/{pkiEzsignfoldersignerassociationID}
type EzsignfoldersignerassociationEditObjectV1Response struct {
	CommonResponse
}

type _EzsignfoldersignerassociationEditObjectV1Response EzsignfoldersignerassociationEditObjectV1Response

// NewEzsignfoldersignerassociationEditObjectV1Response instantiates a new EzsignfoldersignerassociationEditObjectV1Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEzsignfoldersignerassociationEditObjectV1Response(objDebugPayload CommonResponseObjDebugPayload) *EzsignfoldersignerassociationEditObjectV1Response {
	this := EzsignfoldersignerassociationEditObjectV1Response{}
	this.ObjDebugPayload = objDebugPayload
	return &this
}

// NewEzsignfoldersignerassociationEditObjectV1ResponseWithDefaults instantiates a new EzsignfoldersignerassociationEditObjectV1Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEzsignfoldersignerassociationEditObjectV1ResponseWithDefaults() *EzsignfoldersignerassociationEditObjectV1Response {
	this := EzsignfoldersignerassociationEditObjectV1Response{}
	return &this
}

func (o EzsignfoldersignerassociationEditObjectV1Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EzsignfoldersignerassociationEditObjectV1Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

func (o *EzsignfoldersignerassociationEditObjectV1Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"objDebugPayload",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEzsignfoldersignerassociationEditObjectV1Response := _EzsignfoldersignerassociationEditObjectV1Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEzsignfoldersignerassociationEditObjectV1Response)

	if err != nil {
		return err
	}

	*o = EzsignfoldersignerassociationEditObjectV1Response(varEzsignfoldersignerassociationEditObjectV1Response)

	return err
}

type NullableEzsignfoldersignerassociationEditObjectV1Response struct {
	value *EzsignfoldersignerassociationEditObjectV1Response
	isSet bool
}

func (v NullableEzsignfoldersignerassociationEditObjectV1Response) Get() *EzsignfoldersignerassociationEditObjectV1Response {
	return v.value
}

func (v *NullableEzsignfoldersignerassociationEditObjectV1Response) Set(val *EzsignfoldersignerassociationEditObjectV1Response) {
	v.value = val
	v.isSet = true
}

func (v NullableEzsignfoldersignerassociationEditObjectV1Response) IsSet() bool {
	return v.isSet
}

func (v *NullableEzsignfoldersignerassociationEditObjectV1Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEzsignfoldersignerassociationEditObjectV1Response(val *EzsignfoldersignerassociationEditObjectV1Response) *NullableEzsignfoldersignerassociationEditObjectV1Response {
	return &NullableEzsignfoldersignerassociationEditObjectV1Response{value: val, isSet: true}
}

func (v NullableEzsignfoldersignerassociationEditObjectV1Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEzsignfoldersignerassociationEditObjectV1Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


