/*
eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

API version: 1.2.2
Contact: support-api@ezmax.ca
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eZmaxApi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SupplyEditObjectV1Request type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SupplyEditObjectV1Request{}

// SupplyEditObjectV1Request Request for PUT /1/object/supply/{pkiSupplyID}
type SupplyEditObjectV1Request struct {
	ObjSupply SupplyRequestCompound `json:"objSupply"`
}

type _SupplyEditObjectV1Request SupplyEditObjectV1Request

// NewSupplyEditObjectV1Request instantiates a new SupplyEditObjectV1Request object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSupplyEditObjectV1Request(objSupply SupplyRequestCompound) *SupplyEditObjectV1Request {
	this := SupplyEditObjectV1Request{}
	this.ObjSupply = objSupply
	return &this
}

// NewSupplyEditObjectV1RequestWithDefaults instantiates a new SupplyEditObjectV1Request object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSupplyEditObjectV1RequestWithDefaults() *SupplyEditObjectV1Request {
	this := SupplyEditObjectV1Request{}
	return &this
}

// GetObjSupply returns the ObjSupply field value
func (o *SupplyEditObjectV1Request) GetObjSupply() SupplyRequestCompound {
	if o == nil {
		var ret SupplyRequestCompound
		return ret
	}

	return o.ObjSupply
}

// GetObjSupplyOk returns a tuple with the ObjSupply field value
// and a boolean to check if the value has been set.
func (o *SupplyEditObjectV1Request) GetObjSupplyOk() (*SupplyRequestCompound, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjSupply, true
}

// SetObjSupply sets field value
func (o *SupplyEditObjectV1Request) SetObjSupply(v SupplyRequestCompound) {
	o.ObjSupply = v
}

func (o SupplyEditObjectV1Request) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SupplyEditObjectV1Request) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["objSupply"] = o.ObjSupply
	return toSerialize, nil
}

func (o *SupplyEditObjectV1Request) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"objSupply",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSupplyEditObjectV1Request := _SupplyEditObjectV1Request{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSupplyEditObjectV1Request)

	if err != nil {
		return err
	}

	*o = SupplyEditObjectV1Request(varSupplyEditObjectV1Request)

	return err
}

type NullableSupplyEditObjectV1Request struct {
	value *SupplyEditObjectV1Request
	isSet bool
}

func (v NullableSupplyEditObjectV1Request) Get() *SupplyEditObjectV1Request {
	return v.value
}

func (v *NullableSupplyEditObjectV1Request) Set(val *SupplyEditObjectV1Request) {
	v.value = val
	v.isSet = true
}

func (v NullableSupplyEditObjectV1Request) IsSet() bool {
	return v.isSet
}

func (v *NullableSupplyEditObjectV1Request) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSupplyEditObjectV1Request(val *SupplyEditObjectV1Request) *NullableSupplyEditObjectV1Request {
	return &NullableSupplyEditObjectV1Request{value: val, isSet: true}
}

func (v NullableSupplyEditObjectV1Request) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSupplyEditObjectV1Request) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


