/*
eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

API version: 1.3.1
Contact: support-api@ezmax.ca
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eZmaxApi

import (
	"encoding/json"
)

// checks if the MultilingualEzmaxpartnerDescription type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MultilingualEzmaxpartnerDescription{}

// MultilingualEzmaxpartnerDescription Description of the Ezmaxpartner
type MultilingualEzmaxpartnerDescription struct {
	// The description of the Ezmaxpartner in french
	SEzmaxpartnerDescription1 *string `json:"sEzmaxpartnerDescription1,omitempty"`
	// The description of the Ezmaxpartner in english
	SEzmaxpartnerDescription2 *string `json:"sEzmaxpartnerDescription2,omitempty"`
}

// NewMultilingualEzmaxpartnerDescription instantiates a new MultilingualEzmaxpartnerDescription object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMultilingualEzmaxpartnerDescription() *MultilingualEzmaxpartnerDescription {
	this := MultilingualEzmaxpartnerDescription{}
	return &this
}

// NewMultilingualEzmaxpartnerDescriptionWithDefaults instantiates a new MultilingualEzmaxpartnerDescription object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMultilingualEzmaxpartnerDescriptionWithDefaults() *MultilingualEzmaxpartnerDescription {
	this := MultilingualEzmaxpartnerDescription{}
	return &this
}

// GetSEzmaxpartnerDescription1 returns the SEzmaxpartnerDescription1 field value if set, zero value otherwise.
func (o *MultilingualEzmaxpartnerDescription) GetSEzmaxpartnerDescription1() string {
	if o == nil || IsNil(o.SEzmaxpartnerDescription1) {
		var ret string
		return ret
	}
	return *o.SEzmaxpartnerDescription1
}

// GetSEzmaxpartnerDescription1Ok returns a tuple with the SEzmaxpartnerDescription1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultilingualEzmaxpartnerDescription) GetSEzmaxpartnerDescription1Ok() (*string, bool) {
	if o == nil || IsNil(o.SEzmaxpartnerDescription1) {
		return nil, false
	}
	return o.SEzmaxpartnerDescription1, true
}

// HasSEzmaxpartnerDescription1 returns a boolean if a field has been set.
func (o *MultilingualEzmaxpartnerDescription) HasSEzmaxpartnerDescription1() bool {
	if o != nil && !IsNil(o.SEzmaxpartnerDescription1) {
		return true
	}

	return false
}

// SetSEzmaxpartnerDescription1 gets a reference to the given string and assigns it to the SEzmaxpartnerDescription1 field.
func (o *MultilingualEzmaxpartnerDescription) SetSEzmaxpartnerDescription1(v string) {
	o.SEzmaxpartnerDescription1 = &v
}

// GetSEzmaxpartnerDescription2 returns the SEzmaxpartnerDescription2 field value if set, zero value otherwise.
func (o *MultilingualEzmaxpartnerDescription) GetSEzmaxpartnerDescription2() string {
	if o == nil || IsNil(o.SEzmaxpartnerDescription2) {
		var ret string
		return ret
	}
	return *o.SEzmaxpartnerDescription2
}

// GetSEzmaxpartnerDescription2Ok returns a tuple with the SEzmaxpartnerDescription2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultilingualEzmaxpartnerDescription) GetSEzmaxpartnerDescription2Ok() (*string, bool) {
	if o == nil || IsNil(o.SEzmaxpartnerDescription2) {
		return nil, false
	}
	return o.SEzmaxpartnerDescription2, true
}

// HasSEzmaxpartnerDescription2 returns a boolean if a field has been set.
func (o *MultilingualEzmaxpartnerDescription) HasSEzmaxpartnerDescription2() bool {
	if o != nil && !IsNil(o.SEzmaxpartnerDescription2) {
		return true
	}

	return false
}

// SetSEzmaxpartnerDescription2 gets a reference to the given string and assigns it to the SEzmaxpartnerDescription2 field.
func (o *MultilingualEzmaxpartnerDescription) SetSEzmaxpartnerDescription2(v string) {
	o.SEzmaxpartnerDescription2 = &v
}

func (o MultilingualEzmaxpartnerDescription) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MultilingualEzmaxpartnerDescription) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SEzmaxpartnerDescription1) {
		toSerialize["sEzmaxpartnerDescription1"] = o.SEzmaxpartnerDescription1
	}
	if !IsNil(o.SEzmaxpartnerDescription2) {
		toSerialize["sEzmaxpartnerDescription2"] = o.SEzmaxpartnerDescription2
	}
	return toSerialize, nil
}

type NullableMultilingualEzmaxpartnerDescription struct {
	value *MultilingualEzmaxpartnerDescription
	isSet bool
}

func (v NullableMultilingualEzmaxpartnerDescription) Get() *MultilingualEzmaxpartnerDescription {
	return v.value
}

func (v *NullableMultilingualEzmaxpartnerDescription) Set(val *MultilingualEzmaxpartnerDescription) {
	v.value = val
	v.isSet = true
}

func (v NullableMultilingualEzmaxpartnerDescription) IsSet() bool {
	return v.isSet
}

func (v *NullableMultilingualEzmaxpartnerDescription) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMultilingualEzmaxpartnerDescription(val *MultilingualEzmaxpartnerDescription) *NullableMultilingualEzmaxpartnerDescription {
	return &NullableMultilingualEzmaxpartnerDescription{value: val, isSet: true}
}

func (v NullableMultilingualEzmaxpartnerDescription) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMultilingualEzmaxpartnerDescription) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


