/*
eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

API version: 1.2.1
Contact: support-api@ezmax.ca
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eZmaxApi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EzsignsignatureResponseCompoundV3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EzsignsignatureResponseCompoundV3{}

// EzsignsignatureResponseCompoundV3 An Ezsignsignature Object and children to create a complete structure
type EzsignsignatureResponseCompoundV3 struct {
	EzsignsignatureResponse
	// Whether the Ezsignsignature has a custom date format or not. (Only possible when eEzsignsignatureType is **Name** or **Handwritten**)
	BEzsignsignatureCustomdate *bool `json:"bEzsignsignatureCustomdate,omitempty"`
	// An array of custom date blocks that will be filled at the time of signature.  Can only be used if bEzsignsignatureCustomdate is true.  Use an empty array if you don't want to have a date at all.
	AObjEzsignsignaturecustomdate []EzsignsignaturecustomdateResponseCompoundV2 `json:"a_objEzsignsignaturecustomdate,omitempty"`
	ObjCreditcardtransaction *CustomCreditcardtransactionResponse `json:"objCreditcardtransaction,omitempty"`
	AObjEzsignelementdependency []EzsignelementdependencyResponseCompound `json:"a_objEzsignelementdependency,omitempty"`
}

type _EzsignsignatureResponseCompoundV3 EzsignsignatureResponseCompoundV3

// NewEzsignsignatureResponseCompoundV3 instantiates a new EzsignsignatureResponseCompoundV3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEzsignsignatureResponseCompoundV3(pkiEzsignsignatureID int32, fkiEzsigndocumentID int32, fkiEzsignfoldersignerassociationID int32, iEzsignpagePagenumber int32, iEzsignsignatureX int32, iEzsignsignatureY int32, iEzsignsignatureStep int32, eEzsignsignatureType FieldEEzsignsignatureType, objContactName CustomContactNameResponse) *EzsignsignatureResponseCompoundV3 {
	this := EzsignsignatureResponseCompoundV3{}
	this.PkiEzsignsignatureID = pkiEzsignsignatureID
	this.FkiEzsigndocumentID = fkiEzsigndocumentID
	this.FkiEzsignfoldersignerassociationID = fkiEzsignfoldersignerassociationID
	this.IEzsignpagePagenumber = iEzsignpagePagenumber
	this.IEzsignsignatureX = iEzsignsignatureX
	this.IEzsignsignatureY = iEzsignsignatureY
	this.IEzsignsignatureStep = iEzsignsignatureStep
	this.EEzsignsignatureType = eEzsignsignatureType
	this.ObjContactName = objContactName
	return &this
}

// NewEzsignsignatureResponseCompoundV3WithDefaults instantiates a new EzsignsignatureResponseCompoundV3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEzsignsignatureResponseCompoundV3WithDefaults() *EzsignsignatureResponseCompoundV3 {
	this := EzsignsignatureResponseCompoundV3{}
	return &this
}

// GetBEzsignsignatureCustomdate returns the BEzsignsignatureCustomdate field value if set, zero value otherwise.
func (o *EzsignsignatureResponseCompoundV3) GetBEzsignsignatureCustomdate() bool {
	if o == nil || IsNil(o.BEzsignsignatureCustomdate) {
		var ret bool
		return ret
	}
	return *o.BEzsignsignatureCustomdate
}

// GetBEzsignsignatureCustomdateOk returns a tuple with the BEzsignsignatureCustomdate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EzsignsignatureResponseCompoundV3) GetBEzsignsignatureCustomdateOk() (*bool, bool) {
	if o == nil || IsNil(o.BEzsignsignatureCustomdate) {
		return nil, false
	}
	return o.BEzsignsignatureCustomdate, true
}

// HasBEzsignsignatureCustomdate returns a boolean if a field has been set.
func (o *EzsignsignatureResponseCompoundV3) HasBEzsignsignatureCustomdate() bool {
	if o != nil && !IsNil(o.BEzsignsignatureCustomdate) {
		return true
	}

	return false
}

// SetBEzsignsignatureCustomdate gets a reference to the given bool and assigns it to the BEzsignsignatureCustomdate field.
func (o *EzsignsignatureResponseCompoundV3) SetBEzsignsignatureCustomdate(v bool) {
	o.BEzsignsignatureCustomdate = &v
}

// GetAObjEzsignsignaturecustomdate returns the AObjEzsignsignaturecustomdate field value if set, zero value otherwise.
func (o *EzsignsignatureResponseCompoundV3) GetAObjEzsignsignaturecustomdate() []EzsignsignaturecustomdateResponseCompoundV2 {
	if o == nil || IsNil(o.AObjEzsignsignaturecustomdate) {
		var ret []EzsignsignaturecustomdateResponseCompoundV2
		return ret
	}
	return o.AObjEzsignsignaturecustomdate
}

// GetAObjEzsignsignaturecustomdateOk returns a tuple with the AObjEzsignsignaturecustomdate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EzsignsignatureResponseCompoundV3) GetAObjEzsignsignaturecustomdateOk() ([]EzsignsignaturecustomdateResponseCompoundV2, bool) {
	if o == nil || IsNil(o.AObjEzsignsignaturecustomdate) {
		return nil, false
	}
	return o.AObjEzsignsignaturecustomdate, true
}

// HasAObjEzsignsignaturecustomdate returns a boolean if a field has been set.
func (o *EzsignsignatureResponseCompoundV3) HasAObjEzsignsignaturecustomdate() bool {
	if o != nil && !IsNil(o.AObjEzsignsignaturecustomdate) {
		return true
	}

	return false
}

// SetAObjEzsignsignaturecustomdate gets a reference to the given []EzsignsignaturecustomdateResponseCompoundV2 and assigns it to the AObjEzsignsignaturecustomdate field.
func (o *EzsignsignatureResponseCompoundV3) SetAObjEzsignsignaturecustomdate(v []EzsignsignaturecustomdateResponseCompoundV2) {
	o.AObjEzsignsignaturecustomdate = v
}

// GetObjCreditcardtransaction returns the ObjCreditcardtransaction field value if set, zero value otherwise.
func (o *EzsignsignatureResponseCompoundV3) GetObjCreditcardtransaction() CustomCreditcardtransactionResponse {
	if o == nil || IsNil(o.ObjCreditcardtransaction) {
		var ret CustomCreditcardtransactionResponse
		return ret
	}
	return *o.ObjCreditcardtransaction
}

// GetObjCreditcardtransactionOk returns a tuple with the ObjCreditcardtransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EzsignsignatureResponseCompoundV3) GetObjCreditcardtransactionOk() (*CustomCreditcardtransactionResponse, bool) {
	if o == nil || IsNil(o.ObjCreditcardtransaction) {
		return nil, false
	}
	return o.ObjCreditcardtransaction, true
}

// HasObjCreditcardtransaction returns a boolean if a field has been set.
func (o *EzsignsignatureResponseCompoundV3) HasObjCreditcardtransaction() bool {
	if o != nil && !IsNil(o.ObjCreditcardtransaction) {
		return true
	}

	return false
}

// SetObjCreditcardtransaction gets a reference to the given CustomCreditcardtransactionResponse and assigns it to the ObjCreditcardtransaction field.
func (o *EzsignsignatureResponseCompoundV3) SetObjCreditcardtransaction(v CustomCreditcardtransactionResponse) {
	o.ObjCreditcardtransaction = &v
}

// GetAObjEzsignelementdependency returns the AObjEzsignelementdependency field value if set, zero value otherwise.
func (o *EzsignsignatureResponseCompoundV3) GetAObjEzsignelementdependency() []EzsignelementdependencyResponseCompound {
	if o == nil || IsNil(o.AObjEzsignelementdependency) {
		var ret []EzsignelementdependencyResponseCompound
		return ret
	}
	return o.AObjEzsignelementdependency
}

// GetAObjEzsignelementdependencyOk returns a tuple with the AObjEzsignelementdependency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EzsignsignatureResponseCompoundV3) GetAObjEzsignelementdependencyOk() ([]EzsignelementdependencyResponseCompound, bool) {
	if o == nil || IsNil(o.AObjEzsignelementdependency) {
		return nil, false
	}
	return o.AObjEzsignelementdependency, true
}

// HasAObjEzsignelementdependency returns a boolean if a field has been set.
func (o *EzsignsignatureResponseCompoundV3) HasAObjEzsignelementdependency() bool {
	if o != nil && !IsNil(o.AObjEzsignelementdependency) {
		return true
	}

	return false
}

// SetAObjEzsignelementdependency gets a reference to the given []EzsignelementdependencyResponseCompound and assigns it to the AObjEzsignelementdependency field.
func (o *EzsignsignatureResponseCompoundV3) SetAObjEzsignelementdependency(v []EzsignelementdependencyResponseCompound) {
	o.AObjEzsignelementdependency = v
}

func (o EzsignsignatureResponseCompoundV3) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EzsignsignatureResponseCompoundV3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BEzsignsignatureCustomdate) {
		toSerialize["bEzsignsignatureCustomdate"] = o.BEzsignsignatureCustomdate
	}
	if !IsNil(o.AObjEzsignsignaturecustomdate) {
		toSerialize["a_objEzsignsignaturecustomdate"] = o.AObjEzsignsignaturecustomdate
	}
	if !IsNil(o.ObjCreditcardtransaction) {
		toSerialize["objCreditcardtransaction"] = o.ObjCreditcardtransaction
	}
	if !IsNil(o.AObjEzsignelementdependency) {
		toSerialize["a_objEzsignelementdependency"] = o.AObjEzsignelementdependency
	}
	return toSerialize, nil
}

func (o *EzsignsignatureResponseCompoundV3) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pkiEzsignsignatureID",
		"fkiEzsigndocumentID",
		"fkiEzsignfoldersignerassociationID",
		"iEzsignpagePagenumber",
		"iEzsignsignatureX",
		"iEzsignsignatureY",
		"iEzsignsignatureStep",
		"eEzsignsignatureType",
		"objContactName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEzsignsignatureResponseCompoundV3 := _EzsignsignatureResponseCompoundV3{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEzsignsignatureResponseCompoundV3)

	if err != nil {
		return err
	}

	*o = EzsignsignatureResponseCompoundV3(varEzsignsignatureResponseCompoundV3)

	return err
}

type NullableEzsignsignatureResponseCompoundV3 struct {
	value *EzsignsignatureResponseCompoundV3
	isSet bool
}

func (v NullableEzsignsignatureResponseCompoundV3) Get() *EzsignsignatureResponseCompoundV3 {
	return v.value
}

func (v *NullableEzsignsignatureResponseCompoundV3) Set(val *EzsignsignatureResponseCompoundV3) {
	v.value = val
	v.isSet = true
}

func (v NullableEzsignsignatureResponseCompoundV3) IsSet() bool {
	return v.isSet
}

func (v *NullableEzsignsignatureResponseCompoundV3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEzsignsignatureResponseCompoundV3(val *EzsignsignatureResponseCompoundV3) *NullableEzsignsignatureResponseCompoundV3 {
	return &NullableEzsignsignatureResponseCompoundV3{value: val, isSet: true}
}

func (v NullableEzsignsignatureResponseCompoundV3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEzsignsignatureResponseCompoundV3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


