/*
eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

API version: 1.2.1
Contact: support-api@ezmax.ca
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eZmaxApi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FranchisereferalincomeRequestCompound type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FranchisereferalincomeRequestCompound{}

// FranchisereferalincomeRequestCompound A Franchisereferalincome Object and children to create a complete structure
type FranchisereferalincomeRequestCompound struct {
	FranchisereferalincomeRequest
	ObjAddress *AddressRequest `json:"objAddress,omitempty"`
	AObjContact []ContactRequestCompound `json:"a_objContact"`
}

type _FranchisereferalincomeRequestCompound FranchisereferalincomeRequestCompound

// NewFranchisereferalincomeRequestCompound instantiates a new FranchisereferalincomeRequestCompound object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFranchisereferalincomeRequestCompound(aObjContact []ContactRequestCompound, fkiFranchisebrokerID int32, fkiFranchisereferalincomeprogramID int32, fkiPeriodID int32, dFranchisereferalincomeLoan string, dFranchisereferalincomeFranchiseamount string, dFranchisereferalincomeFranchisoramount string, dFranchisereferalincomeAgentamount string, dtFranchisereferalincomeDisbursed string, tFranchisereferalincomeComment string, fkiFranchiseofficeID int32, sFranchisereferalincomeRemoteid string) *FranchisereferalincomeRequestCompound {
	this := FranchisereferalincomeRequestCompound{}
	this.FkiFranchisebrokerID = fkiFranchisebrokerID
	this.FkiFranchisereferalincomeprogramID = fkiFranchisereferalincomeprogramID
	this.FkiPeriodID = fkiPeriodID
	this.DFranchisereferalincomeLoan = dFranchisereferalincomeLoan
	this.DFranchisereferalincomeFranchiseamount = dFranchisereferalincomeFranchiseamount
	this.DFranchisereferalincomeFranchisoramount = dFranchisereferalincomeFranchisoramount
	this.DFranchisereferalincomeAgentamount = dFranchisereferalincomeAgentamount
	this.DtFranchisereferalincomeDisbursed = dtFranchisereferalincomeDisbursed
	this.TFranchisereferalincomeComment = tFranchisereferalincomeComment
	this.FkiFranchiseofficeID = fkiFranchiseofficeID
	this.SFranchisereferalincomeRemoteid = sFranchisereferalincomeRemoteid
	this.AObjContact = aObjContact
	return &this
}

// NewFranchisereferalincomeRequestCompoundWithDefaults instantiates a new FranchisereferalincomeRequestCompound object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFranchisereferalincomeRequestCompoundWithDefaults() *FranchisereferalincomeRequestCompound {
	this := FranchisereferalincomeRequestCompound{}
	return &this
}

// GetObjAddress returns the ObjAddress field value if set, zero value otherwise.
func (o *FranchisereferalincomeRequestCompound) GetObjAddress() AddressRequest {
	if o == nil || IsNil(o.ObjAddress) {
		var ret AddressRequest
		return ret
	}
	return *o.ObjAddress
}

// GetObjAddressOk returns a tuple with the ObjAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FranchisereferalincomeRequestCompound) GetObjAddressOk() (*AddressRequest, bool) {
	if o == nil || IsNil(o.ObjAddress) {
		return nil, false
	}
	return o.ObjAddress, true
}

// HasObjAddress returns a boolean if a field has been set.
func (o *FranchisereferalincomeRequestCompound) HasObjAddress() bool {
	if o != nil && !IsNil(o.ObjAddress) {
		return true
	}

	return false
}

// SetObjAddress gets a reference to the given AddressRequest and assigns it to the ObjAddress field.
func (o *FranchisereferalincomeRequestCompound) SetObjAddress(v AddressRequest) {
	o.ObjAddress = &v
}

// GetAObjContact returns the AObjContact field value
func (o *FranchisereferalincomeRequestCompound) GetAObjContact() []ContactRequestCompound {
	if o == nil {
		var ret []ContactRequestCompound
		return ret
	}

	return o.AObjContact
}

// GetAObjContactOk returns a tuple with the AObjContact field value
// and a boolean to check if the value has been set.
func (o *FranchisereferalincomeRequestCompound) GetAObjContactOk() ([]ContactRequestCompound, bool) {
	if o == nil {
		return nil, false
	}
	return o.AObjContact, true
}

// SetAObjContact sets field value
func (o *FranchisereferalincomeRequestCompound) SetAObjContact(v []ContactRequestCompound) {
	o.AObjContact = v
}

func (o FranchisereferalincomeRequestCompound) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FranchisereferalincomeRequestCompound) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ObjAddress) {
		toSerialize["objAddress"] = o.ObjAddress
	}
	toSerialize["a_objContact"] = o.AObjContact
	return toSerialize, nil
}

func (o *FranchisereferalincomeRequestCompound) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"a_objContact",
		"fkiFranchisebrokerID",
		"fkiFranchisereferalincomeprogramID",
		"fkiPeriodID",
		"dFranchisereferalincomeLoan",
		"dFranchisereferalincomeFranchiseamount",
		"dFranchisereferalincomeFranchisoramount",
		"dFranchisereferalincomeAgentamount",
		"dtFranchisereferalincomeDisbursed",
		"tFranchisereferalincomeComment",
		"fkiFranchiseofficeID",
		"sFranchisereferalincomeRemoteid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFranchisereferalincomeRequestCompound := _FranchisereferalincomeRequestCompound{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFranchisereferalincomeRequestCompound)

	if err != nil {
		return err
	}

	*o = FranchisereferalincomeRequestCompound(varFranchisereferalincomeRequestCompound)

	return err
}

type NullableFranchisereferalincomeRequestCompound struct {
	value *FranchisereferalincomeRequestCompound
	isSet bool
}

func (v NullableFranchisereferalincomeRequestCompound) Get() *FranchisereferalincomeRequestCompound {
	return v.value
}

func (v *NullableFranchisereferalincomeRequestCompound) Set(val *FranchisereferalincomeRequestCompound) {
	v.value = val
	v.isSet = true
}

func (v NullableFranchisereferalincomeRequestCompound) IsSet() bool {
	return v.isSet
}

func (v *NullableFranchisereferalincomeRequestCompound) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFranchisereferalincomeRequestCompound(val *FranchisereferalincomeRequestCompound) *NullableFranchisereferalincomeRequestCompound {
	return &NullableFranchisereferalincomeRequestCompound{value: val, isSet: true}
}

func (v NullableFranchisereferalincomeRequestCompound) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFranchisereferalincomeRequestCompound) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


