/*
eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

API version: 1.2.1
Contact: support-api@ezmax.ca
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eZmaxApi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EzsignfolderGetCommunicationListV1Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EzsignfolderGetCommunicationListV1Response{}

// EzsignfolderGetCommunicationListV1Response Response for GET /1/object/ezsignfolder/{pkiEzsignfolderID}/getCommunicationList
type EzsignfolderGetCommunicationListV1Response struct {
	CommonResponseGetList
	MPayload EzsignfolderGetCommunicationListV1ResponseMPayload `json:"mPayload"`
}

type _EzsignfolderGetCommunicationListV1Response EzsignfolderGetCommunicationListV1Response

// NewEzsignfolderGetCommunicationListV1Response instantiates a new EzsignfolderGetCommunicationListV1Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEzsignfolderGetCommunicationListV1Response(mPayload EzsignfolderGetCommunicationListV1ResponseMPayload, objDebugPayload CommonResponseObjDebugPayloadGetList) *EzsignfolderGetCommunicationListV1Response {
	this := EzsignfolderGetCommunicationListV1Response{}
	this.ObjDebugPayload = objDebugPayload
	this.MPayload = mPayload
	return &this
}

// NewEzsignfolderGetCommunicationListV1ResponseWithDefaults instantiates a new EzsignfolderGetCommunicationListV1Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEzsignfolderGetCommunicationListV1ResponseWithDefaults() *EzsignfolderGetCommunicationListV1Response {
	this := EzsignfolderGetCommunicationListV1Response{}
	return &this
}

// GetMPayload returns the MPayload field value
func (o *EzsignfolderGetCommunicationListV1Response) GetMPayload() EzsignfolderGetCommunicationListV1ResponseMPayload {
	if o == nil {
		var ret EzsignfolderGetCommunicationListV1ResponseMPayload
		return ret
	}

	return o.MPayload
}

// GetMPayloadOk returns a tuple with the MPayload field value
// and a boolean to check if the value has been set.
func (o *EzsignfolderGetCommunicationListV1Response) GetMPayloadOk() (*EzsignfolderGetCommunicationListV1ResponseMPayload, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MPayload, true
}

// SetMPayload sets field value
func (o *EzsignfolderGetCommunicationListV1Response) SetMPayload(v EzsignfolderGetCommunicationListV1ResponseMPayload) {
	o.MPayload = v
}

func (o EzsignfolderGetCommunicationListV1Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EzsignfolderGetCommunicationListV1Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mPayload"] = o.MPayload
	return toSerialize, nil
}

func (o *EzsignfolderGetCommunicationListV1Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mPayload",
		"objDebugPayload",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEzsignfolderGetCommunicationListV1Response := _EzsignfolderGetCommunicationListV1Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEzsignfolderGetCommunicationListV1Response)

	if err != nil {
		return err
	}

	*o = EzsignfolderGetCommunicationListV1Response(varEzsignfolderGetCommunicationListV1Response)

	return err
}

type NullableEzsignfolderGetCommunicationListV1Response struct {
	value *EzsignfolderGetCommunicationListV1Response
	isSet bool
}

func (v NullableEzsignfolderGetCommunicationListV1Response) Get() *EzsignfolderGetCommunicationListV1Response {
	return v.value
}

func (v *NullableEzsignfolderGetCommunicationListV1Response) Set(val *EzsignfolderGetCommunicationListV1Response) {
	v.value = val
	v.isSet = true
}

func (v NullableEzsignfolderGetCommunicationListV1Response) IsSet() bool {
	return v.isSet
}

func (v *NullableEzsignfolderGetCommunicationListV1Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEzsignfolderGetCommunicationListV1Response(val *EzsignfolderGetCommunicationListV1Response) *NullableEzsignfolderGetCommunicationListV1Response {
	return &NullableEzsignfolderGetCommunicationListV1Response{value: val, isSet: true}
}

func (v NullableEzsignfolderGetCommunicationListV1Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEzsignfolderGetCommunicationListV1Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


