/*
eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

API version: 1.3.4
Contact: support-api@ezmax.ca
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eZmaxApi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BankaccountBatchDownloadV1Request type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BankaccountBatchDownloadV1Request{}

// BankaccountBatchDownloadV1Request Request for POST /1/object/bankaccount/{pkiBankaccountID}/batchDownload
type BankaccountBatchDownloadV1Request struct {
	APkiAttachmentID []int32 `json:"a_pkiAttachmentID"`
}

type _BankaccountBatchDownloadV1Request BankaccountBatchDownloadV1Request

// NewBankaccountBatchDownloadV1Request instantiates a new BankaccountBatchDownloadV1Request object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBankaccountBatchDownloadV1Request(aPkiAttachmentID []int32) *BankaccountBatchDownloadV1Request {
	this := BankaccountBatchDownloadV1Request{}
	this.APkiAttachmentID = aPkiAttachmentID
	return &this
}

// NewBankaccountBatchDownloadV1RequestWithDefaults instantiates a new BankaccountBatchDownloadV1Request object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBankaccountBatchDownloadV1RequestWithDefaults() *BankaccountBatchDownloadV1Request {
	this := BankaccountBatchDownloadV1Request{}
	return &this
}

// GetAPkiAttachmentID returns the APkiAttachmentID field value
func (o *BankaccountBatchDownloadV1Request) GetAPkiAttachmentID() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.APkiAttachmentID
}

// GetAPkiAttachmentIDOk returns a tuple with the APkiAttachmentID field value
// and a boolean to check if the value has been set.
func (o *BankaccountBatchDownloadV1Request) GetAPkiAttachmentIDOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.APkiAttachmentID, true
}

// SetAPkiAttachmentID sets field value
func (o *BankaccountBatchDownloadV1Request) SetAPkiAttachmentID(v []int32) {
	o.APkiAttachmentID = v
}

func (o BankaccountBatchDownloadV1Request) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BankaccountBatchDownloadV1Request) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["a_pkiAttachmentID"] = o.APkiAttachmentID
	return toSerialize, nil
}

func (o *BankaccountBatchDownloadV1Request) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"a_pkiAttachmentID",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBankaccountBatchDownloadV1Request := _BankaccountBatchDownloadV1Request{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBankaccountBatchDownloadV1Request)

	if err != nil {
		return err
	}

	*o = BankaccountBatchDownloadV1Request(varBankaccountBatchDownloadV1Request)

	return err
}

type NullableBankaccountBatchDownloadV1Request struct {
	value *BankaccountBatchDownloadV1Request
	isSet bool
}

func (v NullableBankaccountBatchDownloadV1Request) Get() *BankaccountBatchDownloadV1Request {
	return v.value
}

func (v *NullableBankaccountBatchDownloadV1Request) Set(val *BankaccountBatchDownloadV1Request) {
	v.value = val
	v.isSet = true
}

func (v NullableBankaccountBatchDownloadV1Request) IsSet() bool {
	return v.isSet
}

func (v *NullableBankaccountBatchDownloadV1Request) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBankaccountBatchDownloadV1Request(val *BankaccountBatchDownloadV1Request) *NullableBankaccountBatchDownloadV1Request {
	return &NullableBankaccountBatchDownloadV1Request{value: val, isSet: true}
}

func (v NullableBankaccountBatchDownloadV1Request) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBankaccountBatchDownloadV1Request) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


