/*
eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

API version: 1.2.1
Contact: support-api@ezmax.ca
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eZmaxApi

import (
	"encoding/json"
)

// checks if the CommunicationexternalrecipientRequestCompound type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommunicationexternalrecipientRequestCompound{}

// CommunicationexternalrecipientRequestCompound A Communicationexternalrecipient Object and children
type CommunicationexternalrecipientRequestCompound struct {
	CommunicationexternalrecipientRequest
}

// NewCommunicationexternalrecipientRequestCompound instantiates a new CommunicationexternalrecipientRequestCompound object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommunicationexternalrecipientRequestCompound() *CommunicationexternalrecipientRequestCompound {
	this := CommunicationexternalrecipientRequestCompound{}
	return &this
}

// NewCommunicationexternalrecipientRequestCompoundWithDefaults instantiates a new CommunicationexternalrecipientRequestCompound object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommunicationexternalrecipientRequestCompoundWithDefaults() *CommunicationexternalrecipientRequestCompound {
	this := CommunicationexternalrecipientRequestCompound{}
	return &this
}

func (o CommunicationexternalrecipientRequestCompound) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommunicationexternalrecipientRequestCompound) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableCommunicationexternalrecipientRequestCompound struct {
	value *CommunicationexternalrecipientRequestCompound
	isSet bool
}

func (v NullableCommunicationexternalrecipientRequestCompound) Get() *CommunicationexternalrecipientRequestCompound {
	return v.value
}

func (v *NullableCommunicationexternalrecipientRequestCompound) Set(val *CommunicationexternalrecipientRequestCompound) {
	v.value = val
	v.isSet = true
}

func (v NullableCommunicationexternalrecipientRequestCompound) IsSet() bool {
	return v.isSet
}

func (v *NullableCommunicationexternalrecipientRequestCompound) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommunicationexternalrecipientRequestCompound(val *CommunicationexternalrecipientRequestCompound) *NullableCommunicationexternalrecipientRequestCompound {
	return &NullableCommunicationexternalrecipientRequestCompound{value: val, isSet: true}
}

func (v NullableCommunicationexternalrecipientRequestCompound) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommunicationexternalrecipientRequestCompound) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


