/*
eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

API version: 1.3.0
Contact: support-api@ezmax.ca
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eZmaxApi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BuyercontractImportIntoEDMV1Request type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BuyercontractImportIntoEDMV1Request{}

// BuyercontractImportIntoEDMV1Request Request for POST /1/object/buyercontract/{pkiBuyercontractID}/importIntoEDM
type BuyercontractImportIntoEDMV1Request struct {
	AObjAttachment []CustomAttachmentImportIntoEDMRequest `json:"a_objAttachment"`
}

type _BuyercontractImportIntoEDMV1Request BuyercontractImportIntoEDMV1Request

// NewBuyercontractImportIntoEDMV1Request instantiates a new BuyercontractImportIntoEDMV1Request object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuyercontractImportIntoEDMV1Request(aObjAttachment []CustomAttachmentImportIntoEDMRequest) *BuyercontractImportIntoEDMV1Request {
	this := BuyercontractImportIntoEDMV1Request{}
	this.AObjAttachment = aObjAttachment
	return &this
}

// NewBuyercontractImportIntoEDMV1RequestWithDefaults instantiates a new BuyercontractImportIntoEDMV1Request object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuyercontractImportIntoEDMV1RequestWithDefaults() *BuyercontractImportIntoEDMV1Request {
	this := BuyercontractImportIntoEDMV1Request{}
	return &this
}

// GetAObjAttachment returns the AObjAttachment field value
func (o *BuyercontractImportIntoEDMV1Request) GetAObjAttachment() []CustomAttachmentImportIntoEDMRequest {
	if o == nil {
		var ret []CustomAttachmentImportIntoEDMRequest
		return ret
	}

	return o.AObjAttachment
}

// GetAObjAttachmentOk returns a tuple with the AObjAttachment field value
// and a boolean to check if the value has been set.
func (o *BuyercontractImportIntoEDMV1Request) GetAObjAttachmentOk() ([]CustomAttachmentImportIntoEDMRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.AObjAttachment, true
}

// SetAObjAttachment sets field value
func (o *BuyercontractImportIntoEDMV1Request) SetAObjAttachment(v []CustomAttachmentImportIntoEDMRequest) {
	o.AObjAttachment = v
}

func (o BuyercontractImportIntoEDMV1Request) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BuyercontractImportIntoEDMV1Request) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["a_objAttachment"] = o.AObjAttachment
	return toSerialize, nil
}

func (o *BuyercontractImportIntoEDMV1Request) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"a_objAttachment",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBuyercontractImportIntoEDMV1Request := _BuyercontractImportIntoEDMV1Request{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBuyercontractImportIntoEDMV1Request)

	if err != nil {
		return err
	}

	*o = BuyercontractImportIntoEDMV1Request(varBuyercontractImportIntoEDMV1Request)

	return err
}

type NullableBuyercontractImportIntoEDMV1Request struct {
	value *BuyercontractImportIntoEDMV1Request
	isSet bool
}

func (v NullableBuyercontractImportIntoEDMV1Request) Get() *BuyercontractImportIntoEDMV1Request {
	return v.value
}

func (v *NullableBuyercontractImportIntoEDMV1Request) Set(val *BuyercontractImportIntoEDMV1Request) {
	v.value = val
	v.isSet = true
}

func (v NullableBuyercontractImportIntoEDMV1Request) IsSet() bool {
	return v.isSet
}

func (v *NullableBuyercontractImportIntoEDMV1Request) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuyercontractImportIntoEDMV1Request(val *BuyercontractImportIntoEDMV1Request) *NullableBuyercontractImportIntoEDMV1Request {
	return &NullableBuyercontractImportIntoEDMV1Request{value: val, isSet: true}
}

func (v NullableBuyercontractImportIntoEDMV1Request) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuyercontractImportIntoEDMV1Request) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


