/*
eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

API version: 1.3.1
Contact: support-api@ezmax.ca
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eZmaxApi

import (
	"encoding/json"
	"fmt"
)

// FieldEEzsigntemplatesignaturepaymentdetailTaxable Whether the Ezsignsignaturepaymentdetail is taxable or not
type FieldEEzsigntemplatesignaturepaymentdetailTaxable string

// List of Field-eEzsigntemplatesignaturepaymentdetailTaxable
const (
	YES FieldEEzsigntemplatesignaturepaymentdetailTaxable = "Yes"
	NO FieldEEzsigntemplatesignaturepaymentdetailTaxable = "No"
	INCLUDED FieldEEzsigntemplatesignaturepaymentdetailTaxable = "Included"
)

// All allowed values of FieldEEzsigntemplatesignaturepaymentdetailTaxable enum
var AllowedFieldEEzsigntemplatesignaturepaymentdetailTaxableEnumValues = []FieldEEzsigntemplatesignaturepaymentdetailTaxable{
	"Yes",
	"No",
	"Included",
}

func (v *FieldEEzsigntemplatesignaturepaymentdetailTaxable) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := FieldEEzsigntemplatesignaturepaymentdetailTaxable(value)
	for _, existing := range AllowedFieldEEzsigntemplatesignaturepaymentdetailTaxableEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid FieldEEzsigntemplatesignaturepaymentdetailTaxable", value)
}

// NewFieldEEzsigntemplatesignaturepaymentdetailTaxableFromValue returns a pointer to a valid FieldEEzsigntemplatesignaturepaymentdetailTaxable
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewFieldEEzsigntemplatesignaturepaymentdetailTaxableFromValue(v string) (*FieldEEzsigntemplatesignaturepaymentdetailTaxable, error) {
	ev := FieldEEzsigntemplatesignaturepaymentdetailTaxable(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for FieldEEzsigntemplatesignaturepaymentdetailTaxable: valid values are %v", v, AllowedFieldEEzsigntemplatesignaturepaymentdetailTaxableEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v FieldEEzsigntemplatesignaturepaymentdetailTaxable) IsValid() bool {
	for _, existing := range AllowedFieldEEzsigntemplatesignaturepaymentdetailTaxableEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Field-eEzsigntemplatesignaturepaymentdetailTaxable value
func (v FieldEEzsigntemplatesignaturepaymentdetailTaxable) Ptr() *FieldEEzsigntemplatesignaturepaymentdetailTaxable {
	return &v
}

type NullableFieldEEzsigntemplatesignaturepaymentdetailTaxable struct {
	value *FieldEEzsigntemplatesignaturepaymentdetailTaxable
	isSet bool
}

func (v NullableFieldEEzsigntemplatesignaturepaymentdetailTaxable) Get() *FieldEEzsigntemplatesignaturepaymentdetailTaxable {
	return v.value
}

func (v *NullableFieldEEzsigntemplatesignaturepaymentdetailTaxable) Set(val *FieldEEzsigntemplatesignaturepaymentdetailTaxable) {
	v.value = val
	v.isSet = true
}

func (v NullableFieldEEzsigntemplatesignaturepaymentdetailTaxable) IsSet() bool {
	return v.isSet
}

func (v *NullableFieldEEzsigntemplatesignaturepaymentdetailTaxable) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFieldEEzsigntemplatesignaturepaymentdetailTaxable(val *FieldEEzsigntemplatesignaturepaymentdetailTaxable) *NullableFieldEEzsigntemplatesignaturepaymentdetailTaxable {
	return &NullableFieldEEzsigntemplatesignaturepaymentdetailTaxable{value: val, isSet: true}
}

func (v NullableFieldEEzsigntemplatesignaturepaymentdetailTaxable) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFieldEEzsigntemplatesignaturepaymentdetailTaxable) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

