/*
eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

API version: 1.2.1
Contact: support-api@ezmax.ca
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eZmaxApi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EzsignsignatureGetObjectV3Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EzsignsignatureGetObjectV3Response{}

// EzsignsignatureGetObjectV3Response Response for GET /3/object/ezsignsignature/{pkiEzsignsignatureID}
type EzsignsignatureGetObjectV3Response struct {
	CommonResponse
	MPayload EzsignsignatureGetObjectV3ResponseMPayload `json:"mPayload"`
}

type _EzsignsignatureGetObjectV3Response EzsignsignatureGetObjectV3Response

// NewEzsignsignatureGetObjectV3Response instantiates a new EzsignsignatureGetObjectV3Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEzsignsignatureGetObjectV3Response(mPayload EzsignsignatureGetObjectV3ResponseMPayload, objDebugPayload CommonResponseObjDebugPayload) *EzsignsignatureGetObjectV3Response {
	this := EzsignsignatureGetObjectV3Response{}
	this.ObjDebugPayload = objDebugPayload
	this.MPayload = mPayload
	return &this
}

// NewEzsignsignatureGetObjectV3ResponseWithDefaults instantiates a new EzsignsignatureGetObjectV3Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEzsignsignatureGetObjectV3ResponseWithDefaults() *EzsignsignatureGetObjectV3Response {
	this := EzsignsignatureGetObjectV3Response{}
	return &this
}

// GetMPayload returns the MPayload field value
func (o *EzsignsignatureGetObjectV3Response) GetMPayload() EzsignsignatureGetObjectV3ResponseMPayload {
	if o == nil {
		var ret EzsignsignatureGetObjectV3ResponseMPayload
		return ret
	}

	return o.MPayload
}

// GetMPayloadOk returns a tuple with the MPayload field value
// and a boolean to check if the value has been set.
func (o *EzsignsignatureGetObjectV3Response) GetMPayloadOk() (*EzsignsignatureGetObjectV3ResponseMPayload, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MPayload, true
}

// SetMPayload sets field value
func (o *EzsignsignatureGetObjectV3Response) SetMPayload(v EzsignsignatureGetObjectV3ResponseMPayload) {
	o.MPayload = v
}

func (o EzsignsignatureGetObjectV3Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EzsignsignatureGetObjectV3Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mPayload"] = o.MPayload
	return toSerialize, nil
}

func (o *EzsignsignatureGetObjectV3Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mPayload",
		"objDebugPayload",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEzsignsignatureGetObjectV3Response := _EzsignsignatureGetObjectV3Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEzsignsignatureGetObjectV3Response)

	if err != nil {
		return err
	}

	*o = EzsignsignatureGetObjectV3Response(varEzsignsignatureGetObjectV3Response)

	return err
}

type NullableEzsignsignatureGetObjectV3Response struct {
	value *EzsignsignatureGetObjectV3Response
	isSet bool
}

func (v NullableEzsignsignatureGetObjectV3Response) Get() *EzsignsignatureGetObjectV3Response {
	return v.value
}

func (v *NullableEzsignsignatureGetObjectV3Response) Set(val *EzsignsignatureGetObjectV3Response) {
	v.value = val
	v.isSet = true
}

func (v NullableEzsignsignatureGetObjectV3Response) IsSet() bool {
	return v.isSet
}

func (v *NullableEzsignsignatureGetObjectV3Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEzsignsignatureGetObjectV3Response(val *EzsignsignatureGetObjectV3Response) *NullableEzsignsignatureGetObjectV3Response {
	return &NullableEzsignsignatureGetObjectV3Response{value: val, isSet: true}
}

func (v NullableEzsignsignatureGetObjectV3Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEzsignsignatureGetObjectV3Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


