/*
eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

API version: 1.2.1
Contact: support-api@ezmax.ca
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eZmaxApi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UsergroupexternalGetAutocompleteV2ResponseMPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsergroupexternalGetAutocompleteV2ResponseMPayload{}

// UsergroupexternalGetAutocompleteV2ResponseMPayload Payload for POST /2/object/usergroupexternal/getAutocomplete
type UsergroupexternalGetAutocompleteV2ResponseMPayload struct {
	// An array of Usergroupexternal autocomplete element response.
	AObjUsergroupexternal []UsergroupexternalAutocompleteElementResponse `json:"a_objUsergroupexternal"`
}

type _UsergroupexternalGetAutocompleteV2ResponseMPayload UsergroupexternalGetAutocompleteV2ResponseMPayload

// NewUsergroupexternalGetAutocompleteV2ResponseMPayload instantiates a new UsergroupexternalGetAutocompleteV2ResponseMPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsergroupexternalGetAutocompleteV2ResponseMPayload(aObjUsergroupexternal []UsergroupexternalAutocompleteElementResponse) *UsergroupexternalGetAutocompleteV2ResponseMPayload {
	this := UsergroupexternalGetAutocompleteV2ResponseMPayload{}
	this.AObjUsergroupexternal = aObjUsergroupexternal
	return &this
}

// NewUsergroupexternalGetAutocompleteV2ResponseMPayloadWithDefaults instantiates a new UsergroupexternalGetAutocompleteV2ResponseMPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsergroupexternalGetAutocompleteV2ResponseMPayloadWithDefaults() *UsergroupexternalGetAutocompleteV2ResponseMPayload {
	this := UsergroupexternalGetAutocompleteV2ResponseMPayload{}
	return &this
}

// GetAObjUsergroupexternal returns the AObjUsergroupexternal field value
func (o *UsergroupexternalGetAutocompleteV2ResponseMPayload) GetAObjUsergroupexternal() []UsergroupexternalAutocompleteElementResponse {
	if o == nil {
		var ret []UsergroupexternalAutocompleteElementResponse
		return ret
	}

	return o.AObjUsergroupexternal
}

// GetAObjUsergroupexternalOk returns a tuple with the AObjUsergroupexternal field value
// and a boolean to check if the value has been set.
func (o *UsergroupexternalGetAutocompleteV2ResponseMPayload) GetAObjUsergroupexternalOk() ([]UsergroupexternalAutocompleteElementResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.AObjUsergroupexternal, true
}

// SetAObjUsergroupexternal sets field value
func (o *UsergroupexternalGetAutocompleteV2ResponseMPayload) SetAObjUsergroupexternal(v []UsergroupexternalAutocompleteElementResponse) {
	o.AObjUsergroupexternal = v
}

func (o UsergroupexternalGetAutocompleteV2ResponseMPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsergroupexternalGetAutocompleteV2ResponseMPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["a_objUsergroupexternal"] = o.AObjUsergroupexternal
	return toSerialize, nil
}

func (o *UsergroupexternalGetAutocompleteV2ResponseMPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"a_objUsergroupexternal",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsergroupexternalGetAutocompleteV2ResponseMPayload := _UsergroupexternalGetAutocompleteV2ResponseMPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsergroupexternalGetAutocompleteV2ResponseMPayload)

	if err != nil {
		return err
	}

	*o = UsergroupexternalGetAutocompleteV2ResponseMPayload(varUsergroupexternalGetAutocompleteV2ResponseMPayload)

	return err
}

type NullableUsergroupexternalGetAutocompleteV2ResponseMPayload struct {
	value *UsergroupexternalGetAutocompleteV2ResponseMPayload
	isSet bool
}

func (v NullableUsergroupexternalGetAutocompleteV2ResponseMPayload) Get() *UsergroupexternalGetAutocompleteV2ResponseMPayload {
	return v.value
}

func (v *NullableUsergroupexternalGetAutocompleteV2ResponseMPayload) Set(val *UsergroupexternalGetAutocompleteV2ResponseMPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableUsergroupexternalGetAutocompleteV2ResponseMPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableUsergroupexternalGetAutocompleteV2ResponseMPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsergroupexternalGetAutocompleteV2ResponseMPayload(val *UsergroupexternalGetAutocompleteV2ResponseMPayload) *NullableUsergroupexternalGetAutocompleteV2ResponseMPayload {
	return &NullableUsergroupexternalGetAutocompleteV2ResponseMPayload{value: val, isSet: true}
}

func (v NullableUsergroupexternalGetAutocompleteV2ResponseMPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsergroupexternalGetAutocompleteV2ResponseMPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


