/*
eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

API version: 1.2.0
Contact: support-api@ezmax.ca
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eZmaxApi

import (
	"encoding/json"
)

// checks if the CommunicationCreateObjectV1ResponseMPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommunicationCreateObjectV1ResponseMPayload{}

// CommunicationCreateObjectV1ResponseMPayload Payload for POST /1/object/communication
type CommunicationCreateObjectV1ResponseMPayload struct {
	// An array of unique IDs representing the object that were requested to be created.  They are returned in the same order as the array containing the objects to be created that was sent in the request.
	APkiCommunicationID []int32 `json:"a_pkiCommunicationID"`
}

// NewCommunicationCreateObjectV1ResponseMPayload instantiates a new CommunicationCreateObjectV1ResponseMPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommunicationCreateObjectV1ResponseMPayload(aPkiCommunicationID []int32) *CommunicationCreateObjectV1ResponseMPayload {
	this := CommunicationCreateObjectV1ResponseMPayload{}
	this.APkiCommunicationID = aPkiCommunicationID
	return &this
}

// NewCommunicationCreateObjectV1ResponseMPayloadWithDefaults instantiates a new CommunicationCreateObjectV1ResponseMPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommunicationCreateObjectV1ResponseMPayloadWithDefaults() *CommunicationCreateObjectV1ResponseMPayload {
	this := CommunicationCreateObjectV1ResponseMPayload{}
	return &this
}

// GetAPkiCommunicationID returns the APkiCommunicationID field value
func (o *CommunicationCreateObjectV1ResponseMPayload) GetAPkiCommunicationID() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.APkiCommunicationID
}

// GetAPkiCommunicationIDOk returns a tuple with the APkiCommunicationID field value
// and a boolean to check if the value has been set.
func (o *CommunicationCreateObjectV1ResponseMPayload) GetAPkiCommunicationIDOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.APkiCommunicationID, true
}

// SetAPkiCommunicationID sets field value
func (o *CommunicationCreateObjectV1ResponseMPayload) SetAPkiCommunicationID(v []int32) {
	o.APkiCommunicationID = v
}

func (o CommunicationCreateObjectV1ResponseMPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommunicationCreateObjectV1ResponseMPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["a_pkiCommunicationID"] = o.APkiCommunicationID
	return toSerialize, nil
}

type NullableCommunicationCreateObjectV1ResponseMPayload struct {
	value *CommunicationCreateObjectV1ResponseMPayload
	isSet bool
}

func (v NullableCommunicationCreateObjectV1ResponseMPayload) Get() *CommunicationCreateObjectV1ResponseMPayload {
	return v.value
}

func (v *NullableCommunicationCreateObjectV1ResponseMPayload) Set(val *CommunicationCreateObjectV1ResponseMPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableCommunicationCreateObjectV1ResponseMPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableCommunicationCreateObjectV1ResponseMPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommunicationCreateObjectV1ResponseMPayload(val *CommunicationCreateObjectV1ResponseMPayload) *NullableCommunicationCreateObjectV1ResponseMPayload {
	return &NullableCommunicationCreateObjectV1ResponseMPayload{value: val, isSet: true}
}

func (v NullableCommunicationCreateObjectV1ResponseMPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommunicationCreateObjectV1ResponseMPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


