/*
eZmax API Definition (Full)

This API expose all the functionnalities for the eZmax and eZsign applications.

API version: 1.2.1
Contact: support-api@ezmax.ca
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eZmaxApi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EzsigntemplatedocumentGetObjectV2Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EzsigntemplatedocumentGetObjectV2Response{}

// EzsigntemplatedocumentGetObjectV2Response Response for GET /2/object/ezsigntemplatedocument/{pkiEzsigntemplatedocumentID}
type EzsigntemplatedocumentGetObjectV2Response struct {
	CommonResponse
	MPayload EzsigntemplatedocumentGetObjectV2ResponseMPayload `json:"mPayload"`
}

type _EzsigntemplatedocumentGetObjectV2Response EzsigntemplatedocumentGetObjectV2Response

// NewEzsigntemplatedocumentGetObjectV2Response instantiates a new EzsigntemplatedocumentGetObjectV2Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEzsigntemplatedocumentGetObjectV2Response(mPayload EzsigntemplatedocumentGetObjectV2ResponseMPayload, objDebugPayload CommonResponseObjDebugPayload) *EzsigntemplatedocumentGetObjectV2Response {
	this := EzsigntemplatedocumentGetObjectV2Response{}
	this.ObjDebugPayload = objDebugPayload
	this.MPayload = mPayload
	return &this
}

// NewEzsigntemplatedocumentGetObjectV2ResponseWithDefaults instantiates a new EzsigntemplatedocumentGetObjectV2Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEzsigntemplatedocumentGetObjectV2ResponseWithDefaults() *EzsigntemplatedocumentGetObjectV2Response {
	this := EzsigntemplatedocumentGetObjectV2Response{}
	return &this
}

// GetMPayload returns the MPayload field value
func (o *EzsigntemplatedocumentGetObjectV2Response) GetMPayload() EzsigntemplatedocumentGetObjectV2ResponseMPayload {
	if o == nil {
		var ret EzsigntemplatedocumentGetObjectV2ResponseMPayload
		return ret
	}

	return o.MPayload
}

// GetMPayloadOk returns a tuple with the MPayload field value
// and a boolean to check if the value has been set.
func (o *EzsigntemplatedocumentGetObjectV2Response) GetMPayloadOk() (*EzsigntemplatedocumentGetObjectV2ResponseMPayload, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MPayload, true
}

// SetMPayload sets field value
func (o *EzsigntemplatedocumentGetObjectV2Response) SetMPayload(v EzsigntemplatedocumentGetObjectV2ResponseMPayload) {
	o.MPayload = v
}

func (o EzsigntemplatedocumentGetObjectV2Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EzsigntemplatedocumentGetObjectV2Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mPayload"] = o.MPayload
	return toSerialize, nil
}

func (o *EzsigntemplatedocumentGetObjectV2Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mPayload",
		"objDebugPayload",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEzsigntemplatedocumentGetObjectV2Response := _EzsigntemplatedocumentGetObjectV2Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEzsigntemplatedocumentGetObjectV2Response)

	if err != nil {
		return err
	}

	*o = EzsigntemplatedocumentGetObjectV2Response(varEzsigntemplatedocumentGetObjectV2Response)

	return err
}

type NullableEzsigntemplatedocumentGetObjectV2Response struct {
	value *EzsigntemplatedocumentGetObjectV2Response
	isSet bool
}

func (v NullableEzsigntemplatedocumentGetObjectV2Response) Get() *EzsigntemplatedocumentGetObjectV2Response {
	return v.value
}

func (v *NullableEzsigntemplatedocumentGetObjectV2Response) Set(val *EzsigntemplatedocumentGetObjectV2Response) {
	v.value = val
	v.isSet = true
}

func (v NullableEzsigntemplatedocumentGetObjectV2Response) IsSet() bool {
	return v.isSet
}

func (v *NullableEzsigntemplatedocumentGetObjectV2Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEzsigntemplatedocumentGetObjectV2Response(val *EzsigntemplatedocumentGetObjectV2Response) *NullableEzsigntemplatedocumentGetObjectV2Response {
	return &NullableEzsigntemplatedocumentGetObjectV2Response{value: val, isSet: true}
}

func (v NullableEzsigntemplatedocumentGetObjectV2Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEzsigntemplatedocumentGetObjectV2Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


